In [5]:
import pandas as pd

baby = pd.read_csv('babynames.csv')
baby

             Name Sex  Count  Year
0            Liam   M  20818  2025
1            Noah   M  20358  2025
2          Oliver   M  14939  2025
3        Theodore   M  13355  2025
4           Henry   M  12020  2025
...           ...  ..    ...   ...
2180881       Ula   F      5  1880
2180882    Vannie   F      5  1880
2180883    Verona   F      5  1880
2180884    Vertie   F      5  1880
2180885     Wilma   F      5  1880

[2180886 rows x 4 columns]

In [7]:
baby.loc[1,'Name']

'Noah'

In [9]:
baby.loc[0:3, 'Name':'Count']

       Name Sex  Count
0      Liam   M  20818
1      Noah   M  20358
2    Oliver   M  14939
3  Theodore   M  13355

In [10]:
baby.loc[:,'Count']

0          20818
1          20358
2          14939
3          13355
4          12020
           ...
2180881        5
2180882        5
2180883        5
2180884        5
2180885        5
Name: Count, Length: 2180886, dtype: int64

In [12]:
counts =baby.loc[:,"Count"]
counts.__class__.__name__

'Series'

In [13]:
baby

             Name Sex  Count  Year
0            Liam   M  20818  2025
1            Noah   M  20358  2025
2          Oliver   M  14939  2025
3        Theodore   M  13355  2025
4           Henry   M  12020  2025
...           ...  ..    ...   ...
2180881       Ula   F      5  1880
2180882    Vannie   F      5  1880
2180883    Verona   F      5  1880
2180884    Vertie   F      5  1880
2180885     Wilma   F      5  1880

[2180886 rows x 4 columns]

In [15]:
baby.loc[:,['Name','Year']]

             Name  Year
0            Liam  2025
1            Noah  2025
2          Oliver  2025
3        Theodore  2025
4           Henry  2025
...           ...   ...
2180881       Ula  1880
2180882    Vannie  1880
2180883    Verona  1880
2180884    Vertie  1880
2180885     Wilma  1880

[2180886 rows x 2 columns]

In [16]:
baby['Name']

0              Liam
1              Noah
2            Oliver
3          Theodore
4             Henry
             ...
2180881         Ula
2180882      Vannie
2180883      Verona
2180884      Vertie
2180885       Wilma
Name: Name, Length: 2180886, dtype: str

In [17]:
baby[['Name','Count']]

             Name  Count
0            Liam  20818
1            Noah  20358
2          Oliver  14939
3        Theodore  13355
4           Henry  12020
...           ...    ...
2180881       Ula      5
2180882    Vannie      5
2180883    Verona      5
2180884    Vertie      5
2180885     Wilma      5

[2180886 rows x 2 columns]

In [19]:
dogs = pd.read_csv('dogs.csv',index_col='breed')
dogs

                   grooming  food_cost    kids    size
breed
Labrador Retriever   weekly      466.0    high  medium
German Shepherd      weekly      466.0  medium   large
Beagle                daily      324.0    high   small
Golden Retriever     weekly      466.0    high  medium
Yorkshire Terrier     daily      324.0     low   small
Bulldog              weekly      466.0  medium  medium
Boxer                weekly      466.0    high  medium

In [20]:
dogs.iloc[0:3,0:2]

                   grooming  food_cost
breed
Labrador Retriever   weekly      466.0
German Shepherd      weekly      466.0
Beagle                daily      324.0

In [22]:
dogs.loc['Labrador Retriever': 'Beagle' , 'grooming' : 'food_cost']

                   grooming  food_cost
breed
Labrador Retriever   weekly      466.0
German Shepherd      weekly      466.0
Beagle                daily      324.0

In [23]:
baby

             Name Sex  Count  Year
0            Liam   M  20818  2025
1            Noah   M  20358  2025
2          Oliver   M  14939  2025
3        Theodore   M  13355  2025
4           Henry   M  12020  2025
...           ...  ..    ...   ...
2180881       Ula   F      5  1880
2180882    Vannie   F      5  1880
2180883    Verona   F      5  1880
2180884    Vertie   F      5  1880
2180885     Wilma   F      5  1880

[2180886 rows x 4 columns]

In [24]:
baby['Year']

0          2025
1          2025
2          2025
3          2025
4          2025
           ...
2180881    1880
2180882    1880
2180883    1880
2180884    1880
2180885    1880
Name: Year, Length: 2180886, dtype: int64

In [25]:
baby['Year'] == 2020

0          False
1          False
2          False
3          False
4          False
           ...
2180881    False
2180882    False
2180883    False
2180884    False
2180885    False
Name: Year, Length: 2180886, dtype: bool

In [26]:
is_2020 =[]
for valuue in baby['Year']:
    is_2020.append(valuue ==2020)

In [27]:
baby.loc[baby['Year']==2020,:]

           Name Sex  Count  Year
158937     Liam   M  19865  2020
158938     Noah   M  18464  2020
158939   Oliver   M  14277  2020
158940   Elijah   M  13238  2020
158941  William   M  12676  2020
...         ...  ..    ...   ...
190518  Zykeria   F      5  2020
190519   Zylynn   F      5  2020
190520   Zymira   F      5  2020
190521  Zynique   F      5  2020
190522   Zynlee   F      5  2020

[31586 rows x 4 columns]

In [28]:
baby[baby['Year']==2020]

           Name Sex  Count  Year
158937     Liam   M  19865  2020
158938     Noah   M  18464  2020
158939   Oliver   M  14277  2020
158940   Elijah   M  13238  2020
158941  William   M  12676  2020
...         ...  ..    ...   ...
190518  Zykeria   F      5  2020
190519   Zylynn   F      5  2020
190520   Zymira   F      5  2020
190521  Zynique   F      5  2020
190522   Zynlee   F      5  2020

[31586 rows x 4 columns]

In [29]:
(baby[baby['Year']==2020]
 .sort_values('Count', ascending=False)
 .head(7))

          Name Sex  Count  Year
158937    Liam   M  19865  2020
158938    Noah   M  18464  2020
172997    Emma   F  15723  2020
158939  Oliver   M  14277  2020
158940  Elijah   M  13238  2020
172998     Ava   F  13201  2020
172999  Sophia   F  13105  2020