In [3]:
# 경고(warning) 메시지 숨기기 - 에러가 아니라 "주의" 문구라서 숨겨도 실행 결과는 같다
import warnings

warnings.filterwarnings("ignore")   # "ignore" = 모든 경고를 무시

## 시리즈

* dict to series

In [4]:
import pandas as pd   # pandas 를 pd 라는 짧은 이름으로 불러오기

# 딕셔너리 → 시리즈 : 키(key)는 인덱스, 값(value)은 데이터가 된다
dict_data = {'a': 1, 'b': 2, 'c': 3}

sr = pd.Series(dict_data)   # 딕셔너리로 시리즈 만들기
print(type(sr))             # <class 'pandas.core.series.Series'>
print()                     # 빈 줄 출력
print(sr)                   # 왼쪽 = 인덱스(a, b, c), 오른쪽 = 값(1, 2, 3)

<class 'pandas.Series'>

a    1
b    2
c    3
dtype: int64

* list to series - series index

In [5]:
import pandas as pd

# 리스트 → 시리즈 : 인덱스를 따로 안 주면 0, 1, 2 ... 정수 인덱스가 자동으로 붙는다
list_data = ['2019-01-02', 3.14, 'ABC', 100, True]   # 자료형이 섞여 있어도 OK (dtype = object)
sr = pd.Series(list_data)

print(sr)

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object

In [6]:
idx = sr.index     # 인덱스(이름표)만 꺼내기 → RangeIndex(start=0, stop=5, step=1)
val = sr.values    # 값만 꺼내기 → numpy 배열
print(idx)
print('\n')        # '\n' = 줄바꿈 (빈 줄을 넣어 결과를 구분)
print(val)

RangeIndex(start=0, stop=5, step=1)


['2019-01-02' 3.14 'ABC' 100 True]

* tuple to series

In [7]:
import pandas as pd

# 튜플 → 시리즈 : index= 로 인덱스 이름을 직접 지정할 수 있다 (값 개수와 같아야 함)
tup_data = ('영인', '2010-05-01', '여', True)
sr = pd.Series(tup_data, index=['이름', '생년월일', '성별', '학생여부'])
print(sr)

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

In [8]:
# 원소를 1개 선택
print(sr.iloc[0])     # iloc = 위치(숫자) 로 선택 → 0번째 값 '영인'
print(sr['이름'])     # 인덱스 이름으로 선택 → '영인'
print('\n')

영인
영인

In [9]:
# 여러 개의 원소를 선택
print(sr.iloc[1 : 3])          # 1번 ~ 2번 위치 (iloc 슬라이싱은 끝 번호 3 미포함)
print('\n')
print(sr[['생년월일', '성별']])  # 이름 여러 개는 리스트 [ ] 로 한 번 더 감싼다

생년월일    2010-05-01
성별               여
dtype: object


생년월일    2010-05-01
성별               여
dtype: object

## 데이터프레임

* dict to dataframe

In [10]:
import pandas as pd

# 딕셔너리 → 데이터프레임 : 키는 열 이름, 값(리스트)은 그 열의 데이터가 된다
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

df = pd.DataFrame(dict_data)   # 3행 x 5열 표. 행 인덱스는 0, 1, 2 자동 생성
print(type(df))                # <class 'pandas.core.frame.DataFrame'>
print('\n')
print(df)

<class 'pandas.DataFrame'>


   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

* list to dataframe

In [11]:
import pandas as pd

# 2차원 리스트 → 데이터프레임 : 안쪽 리스트 하나가 '행' 하나
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']],
                   index=['준서', '예은'],              # 행 이름
                   columns=['나이', '성별', '학교'])    # 열 이름

print(df)            #데이터프레임
print('\n')
print(df.index)      #행 인덱스
print('\n')
print(df.columns)    #열 이름
print('\n')

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중


Index(['준서', '예은'], dtype='str')


Index(['나이', '성별', '학교'], dtype='str')

* 열, 행 이름 변경

In [12]:
import pandas as pd

df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']],
                   index=['준서', '예은'],
                   columns=['나이', '성별', '학교'])

print(df)            #데이터프레임
print('\n')

# rename(columns={기존이름: 새이름}) → 열 이름 변경
#   inplace=True : 원본 df 를 직접 바꿈 (반환값 없음)
df.rename(columns={'나이':'연령', '성별':'남녀', '학교':'소속'}, inplace=True)

# rename(index={...}) → 행 이름 변경
#   inplace 없이 쓰면 새 데이터프레임을 돌려주므로 df = ... 로 다시 저장해야 한다
df = df.rename(index={'준서':'학생1', '예은':'학생2' })

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중


     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

* remove row

In [13]:
import pandas as pd

# 과목별 점수 데이터 (키 = 열 이름)
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])   # 행 이름 = 학생 이름
print(df)
print('\n')

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [14]:
# 행 삭제 : drop(행이름)  (axis 기본값 0 = 행)
df2 = df[:]                     # 전체를 슬라이싱해서 df2 에 담기
df2.drop('우현', inplace=True)  # '우현' 행 삭제, inplace=True → df2 자체를 변경
print(df2)

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [15]:
# 우현, 인아 삭제
df3 = df[:]
df3.drop(['우현', '인아'], axis=0, inplace=True)  # axis=0 : default값(생략 가능) / 여러 행은 리스트로
print(df3)

    수학  영어  음악   체육
서준  90  98  85  100

* remove column

In [16]:
# 열 삭제 : axis=1 을 꼭 써야 한다 (안 쓰면 행에서 '수학' 을 찾다가 KeyError)
df4 = df.copy()  # [:]  / copy() = 원본과 완전히 분리된 복사본 → df4 를 바꿔도 df 는 그대로
df4.drop('수학', axis=1, inplace=True)
df4

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [17]:
# 열 여러 개 삭제 : 리스트로 전달 + axis=1
df5 = df.copy()
df5.drop(['영어', '음악'], axis=1, inplace=True)
print(df5)

    수학   체육
서준  90  100
우현  80   90
인아  70   90

* select row(행)

In [18]:
import pandas as pd

# 행 선택 실습용 데이터 (위 셀에서 행을 지웠을 수 있으니 새로 만든다)
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
print(df)
print('\n')

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [19]:
# 행 인덱스를 사용하여 행 1개를 선택 : loc(문자 인덱스), iloc(숫자 인덱스)
# 서준 행 검색 : loc 인덱서 활용
label1 = df.loc['서준']      # 결과는 시리즈 (열 이름이 인덱스가 됨)

# 0번째 행 검색 : iloc 인덱서 활용
position1 = df.iloc[0]       # 0번째 행 = 서준 → label1 과 같은 결과

print(label1)
print('\n')
print(position1)

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64


수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [20]:
# 행 인덱스를 사용하여 2개 이상의 행 선택
# 서준, 우현 : 인덱싱(loc, iloc 사용)  → 이름/번호를 리스트 [ ] 로 감싼다
label2 = df.loc[['서준', '우현']]
position2 = df.iloc[[0, 1]]
print(label2)
print('\n')
print(position2)
print('\n')

# 서준, 우현 : 슬라이싱(loc, iloc 사용)
label3 = df.loc['서준':'우현']   # loc 슬라이싱은 끝('우현') 포함
position3 = df.iloc[0:2]         # iloc 슬라이싱은 끝(2) 미포함 → 0, 1 행
print(label3)
print('\n')
print(position3)

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90


    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90


    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90


    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

* select column(열)

In [21]:
import pandas as pd

# 열 선택 실습용 데이터 : 이번엔 '이름' 도 하나의 열로 들어 있다 (행 인덱스는 0, 1, 2)
exam_data = {'이름' : [ '서준', '우현', '인아'],
             '수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [22]:
# 열 1개 선택 : df['열이름'] → 시리즈
math1 = df['수학']
print(type(math1))   # Series
math1

<class 'pandas.Series'>

0    90
1    80
2    70
Name: 수학, dtype: int64

In [23]:
# '영어' 점수 출력
english = df.영어      # df.열이름 (속성 방식) 도 가능. 단, 열 이름에 공백/특수문자가 있으면 불가
print(english)
print(type(english))  # Series

0    98
1    89
2    95
Name: 영어, dtype: int64
<class 'pandas.Series'>

In [24]:
# '음악', '체육' 점수 데이터를 선택. 변수 music_gym 에 저장
music_gym = df[['음악', '체육']]   # 대괄호 2겹 [[ ]] : 바깥 = 선택, 안쪽 = 열 이름 리스트
print(type(music_gym))            # DataFrame
music_gym

<class 'pandas.DataFrame'>

    음악   체육
0   85  100
1   95   90
2  100   90

In [25]:
# '수학' 점수 데이터만 선택. 변수 math2에 저장
math2 = df[['수학']]  # DataFrame으로 출력 (열이 1개라도 [[ ]] 면 데이터프레임)
print(type(math2))
math2

<class 'pandas.DataFrame'>

   수학
0  90
1  80
2  70

* select element(요소 검색)

In [26]:
import pandas as pd

# 원소(칸 하나) 선택 실습용 데이터
exam_data = {'이름' : [ '서준', '우현', '인아'],
             '수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [27]:
# 새로운 인덱스로 지정
# '이름' 열을 행 인덱스로 올린다 → 이제 df.loc['서준'] 처럼 이름으로 행을 찾을 수 있다
df.set_index('이름', inplace=True)
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [28]:
# 원소 1개 선택 : 문자 인덱스 / 85 추출
a = df.loc['서준', '음악']   # df.loc[행이름, 열이름]
print(a)

85

In [29]:
# 원소 1개 선택 : 숫자 인덱스  / 85 추출
b = df.iloc[0, 2]   # df.iloc[행번호, 열번호] → 0행(서준), 2열(음악). 번호는 0부터
print(b)

85

In [30]:
# 원소 2개 이상 선택 : 문자 인덱스 / 85, 100
c = df.loc['서준', ['음악', '체육']]   # 열 여러 개는 리스트로 → 결과는 시리즈
c

음악     85
체육    100
Name: 서준, dtype: int64

In [31]:
# 원소 2개 이상 선택 : 숫자 인덱스 / 85, 100
d = df.iloc[0, [2, 3]]   # 0행의 2번(음악), 3번(체육) 열
print(d)

음악     85
체육    100
Name: 서준, dtype: int64

In [32]:
# 원소 2개 이상 선택(슬라이싱) / 85, 100
# 문자 인덱스
e = df.loc['서준', '음악':'체육']   # '음악' 부터 '체육' 까지 (끝 포함)
print(e)

# 숫자 인덱스
f = df.iloc[0, 2:]                 # 2번 열부터 끝까지
print(f)

음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64

In [33]:
# 2개 이상의 행과 열로부터 원소 선택 → 결과는 데이터프레임

# 서준,우현의 음악 체육
g = df.loc[['서준', '우현'], ['음악', '체육']]   # 이름 리스트로 행, 열 선택
print(g)
h = df.iloc[[0, 1], [2, 3]]                      # 번호 리스트로 행, 열 선택
print(h)
i = df.loc['서준':'우현', '음악':'체육']          # 이름 슬라이싱 (끝 포함)
print(i)
j = df.iloc[0:2, 2:]                             # 번호 슬라이싱 (끝 미포함)
print(j)
# → g, h, i, j 모두 같은 결과

    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90

* add column

In [34]:
import pandas as pd

# 열 추가 실습용 데이터
exam_data = {'이름' : [ '서준', '우현', '인아'],
             '수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [35]:
# 열 추가 : df['새 열 이름'] = 값
#   값 하나(80)를 주면 모든 행에 같은 값이 들어간다
df['국어'] = 80
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

* add row

In [36]:
import pandas as pd

# 행 추가 실습용 데이터
exam_data = {'이름' : [ '서준', '우현', '인아'],
             '수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [37]:
# 새로운 행(row)을 추가 - 같은 원소 값을 입력  /  3행에 0값 추가
df.loc[3] = 0   # 없는 행 이름(3) 에 값을 넣으면 새 행이 생긴다. 모든 칸에 0
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0

In [38]:
# 새로운 행(row)을 추가 - 원소 값 여러 개의 배열 입력
df.loc[4] = ['동규', 90, 80, 70, 60]   # 열 개수(5개)와 값 개수가 같아야 한다
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60

In [39]:
# 새로운 행(row)을 추가 - 기존 행을 복사
df.loc['행5'] = df.loc[3]   # 3행의 값을 그대로 복사해 '행5' 라는 새 행으로 추가 (문자 이름도 가능)
print(df)

    이름  수학  영어   음악   체육
0   서준  90  98   85  100
1   우현  80  89   95   90
2   인아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5   0   0   0    0    0

* modify dataframe elements

In [40]:
import pandas as pd

# 원소 값 수정 실습용 데이터
exam_data = {'이름' : [ '서준', '우현', '인아'],
             '수학' : [ 90, 80, 70],
             '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100],
             '체육' : [ 100, 90, 90]}
df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [41]:
# '이름' 열을 행 인덱스로 지정 → 이름으로 행을 찾을 수 있게
df.set_index('이름', inplace=True)
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [42]:
# 서준이의 체육 점수 80으로 수정 / 숫자인덱서
df.iloc[0, 3] = 80   # 선택한 칸에 = 새 값 → 수정
df

    수학  영어   음악  체육
이름
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90

In [43]:
# 서준이의 체육 점수 100로 수정 / 문자인덱서
df.loc['서준', '체육'] = 100
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [44]:
# 서준이의 음악, 체육 점수 50로 수정 / 문자인덱서
df.loc['서준', ['음악', '체육']] = 50   # 여러 칸에 같은 값 하나
df

    수학  영어   음악  체육
이름
서준  90  98   50  50
우현  80  89   95  90
인아  70  95  100  90

In [45]:
# 서준이의 음악, 체육 점수 100, 50로 수정 / 문자인덱서
df.loc['서준', ['음악', '체육']] = 100, 50   # 칸 순서대로 음악=100, 체육=50
df

    수학  영어   음악  체육
이름
서준  90  98  100  50
우현  80  89   95  90
인아  70  95  100  90

* Transpose

In [46]:
import pandas as pd

# 전치(행 ↔ 열 바꾸기) 실습용 데이터
exam_data = {'이름' : [ '서준', '우현', '인아'],
             '수학' : [ 90, 80, 70],
             '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100],
             '체육' : [ 100, 90, 90]}
df = pd.DataFrame(exam_data)
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [47]:
# transpose() : 행과 열을 맞바꾼다 (inplace 옵션이 없으므로 df = ... 로 저장)
df = df.transpose()
df

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

In [48]:
# df.T : transpose() 의 줄임말. 한 번 더 바꾸면 원래 모양으로 돌아온다
df = df.T
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

* set index

In [49]:
# '이름' 열을 행 인덱스로 지정 (inplace 없음 → 결과를 ndf 에 저장, df 는 그대로)
ndf = df.set_index(['이름'])
ndf

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [50]:
# 다른 열('음악')로 인덱스를 다시 지정
#   ※ 기존 인덱스('이름')는 열로 돌아오지 않고 사라진다
ndf2 = ndf.set_index('음악')
ndf2

     수학  영어   체육
음악
85   90  98  100
95   80  89   90
100  70  95   90

In [51]:
# 열 2개를 리스트로 주면 멀티 인덱스(2단 인덱스)가 된다
ndf3 = ndf.set_index(['수학', '음악'])
ndf3

        영어   체육
수학 음악
90 85   98  100
80 95   89   90
70 100  95   90

* set_index 응용(금융)

In [52]:
import pandas as pd

# 주가 데이터 예시 : 날짜(Date), 종가(Close), 거래량(Volume)
data = pd.DataFrame({
    'Date': ['2026-02-01', '2026-02-02', '2026-02-03'],
    'Close': [100, 102, 101],
    'Volume': [15000, 18000, 17000]
})

data

         Date  Close  Volume
0  2026-02-01    100   15000
1  2026-02-02    102   18000
2  2026-02-03    101   17000

In [53]:
# 지금 Date 열의 자료형 확인 → object (날짜가 아니라 그냥 문자열)
data['Date'].dtype

In [54]:
# 날짜 인덱스 지정
# pd.to_datetime() : 문자열 → 날짜 자료형(datetime64)으로 변환
data['Date'] = pd.to_datetime(data['Date'])

In [55]:
# 변환 후 자료형 다시 확인
data['Date'].dtype

# Output - M8 : numpy의 datetime64 타입, us : microseconds(마이크로초)

dtype('<M8[us]')

In [56]:
# .dt 로 날짜의 연, 월, 일만 꺼내기 (날짜 자료형일 때만 사용 가능)
data['Date'].dt.year, data['Date'].dt.month, data['Date'].dt.day

(0    2026
 1    2026
 2    2026
 Name: Date, dtype: int32,
 0    2
 1    2
 2    2
 Name: Date, dtype: int32,
 0    1
 1    2
 2    3
 Name: Date, dtype: int32)

In [57]:
# 날짜(Date)를 행 인덱스로 지정 → 금융 데이터는 보통 날짜를 인덱스로 둔다
df = data.set_index('Date')
df

            Close  Volume
Date
2026-02-01    100   15000
2026-02-02    102   18000
2026-02-03    101   17000

* 멀티 인덱스(금융)

In [58]:
# 날짜별 · 종목별 종가 데이터 (같은 날짜에 종목이 여러 개)
data = pd.DataFrame({
    'Date': ['2026-02-01','2026-02-01','2026-02-02','2026-02-02'],
    '종목': ['삼성','현대','삼성','현대'],
    'Close': [100, 200, 102, 198]
})

data

         Date  종목  Close
0  2026-02-01  삼성    100
1  2026-02-01  현대    200
2  2026-02-02  삼성    102
3  2026-02-02  현대    198

In [59]:
# 멀티인덱스 지정 : Date, 종목
# 1단 = Date, 2단 = 종목 → (날짜, 종목) 묶음이 행 이름이 된다
df = data.set_index(['Date', '종목'])
df

               Close
Date       종목
2026-02-01 삼성    100
           현대    200
2026-02-02 삼성    102
           현대    198

In [60]:
# 멀티 인덱스 선택 : df.loc[(1단 조건, 2단 조건), 열]
#   slice(None) = ':' 와 같은 뜻 → 그 단계는 전부 선택
df.loc[(slice(None), '삼성'), :]  # 모든날짜 + 삼성 + 모든 열 추출

               Close
Date       종목
2026-02-01 삼성    100
2026-02-02 삼성    102

In [61]:
# 2026년 2월 + 삼성
# slice(시작 날짜, 끝 날짜, 간격)  → 날짜 범위 지정 (끝 포함)
df.loc[(slice('2026-02-01', '2026-02-28'), '삼성'), :]

               Close
Date       종목
2026-02-01 삼성    100
2026-02-02 삼성    102

In [62]:
# 2026년 2월 + 현대
df.loc[(slice('2026-02-01', '2026-02-28'), '현대'), :]

               Close
Date       종목
2026-02-01 현대    200
2026-02-02 현대    198

* reindex

In [63]:
import pandas as pd

# reindex 실습용 데이터 : 행 이름 r0, r1, r2
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [64]:
# 인덱스를 [r0, r1, r2, r3, r4]로 재지정
# reindex : 원하는 인덱스 목록으로 행을 다시 배치
#   기존에 없던 r3, r4 는 채울 값이 없어서 NaN(빈 값)이 된다
new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
ndf = df.reindex(new_index)
ndf

     c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN

In [65]:

# reindex로 발생한 NaN값을 숫자 0으로 채우기
new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
ndf2 = df.reindex(new_index, fill_value=0)   # fill_value = 새로 생긴 칸에 넣을 값
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

In [66]:
# 행 인덱스를 정수형으로 초기화
# reset_index : 기존 인덱스(r0, r1, r2)는 'index' 라는 열로 내려가고, 0, 1, 2 가 새 인덱스
ndf = df.reset_index()
ndf

  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15

* sort index

In [67]:
import pandas as pd

# 정렬 실습용 데이터 (c3 의 첫 값을 41 로 바꿔 값 정렬 결과가 눈에 띄게)
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[41,11,12], 'c4':[13,14,15]}

df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
df

    c0  c1  c2  c3  c4
r0   1   4   7  41  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [68]:
# 내림차순으로 행 인덱스 정렬
# sort_index : 행 이름(인덱스) 기준 정렬 / ascending=False → 내림차순 (r2, r1, r0)
ndf = df.sort_index(ascending=False)
print(ndf)

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  41  13

In [69]:
ndf = df.sort_index()  # 기본값은 오름차순 (ascending=True 생략)
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  41  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [70]:
# c3 열을 기준으로 내림차순 정렬
# sort_values(by='열이름') : 인덱스가 아니라 '값' 기준 정렬 → 41, 12, 11 순서
ndf = df.sort_values(by='c3', ascending=False)
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  41  13
r2   3   6   9  12  15
r1   2   5   8  11  14

* series to number

In [71]:
import pandas as pd

# 시리즈 ÷ 숫자 : 모든 원소에 같은 연산이 적용된다
student1 = pd.Series({'국어':100, '영어':80, '수학':90})
print(student1)
print('\n')

# 학생의 과목별 점수를 200으로 나누기
percentage = student1 / 200   # 국어 0.5, 영어 0.4, 수학 0.45
print(percentage)

국어    100
영어     80
수학     90
dtype: int64


국어    0.50
영어    0.40
수학    0.45
dtype: float64

* series to series

In [72]:
import pandas as pd

# 두 학생의 점수 : 과목 순서가 서로 다르다 (연산할 때 순서는 상관없음)
student1 = pd.Series({'국어':100, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90, '영어':80})

print(student1)
print('\n')
print(student2)
print('\n')

국어    100
영어     80
수학     90
dtype: int64


수학    80
국어    90
영어    80
dtype: int64

In [73]:
# 두 학생의 과목별 점수로 사칙연산 수행
#   ※ 시리즈끼리 연산하면 '순서'가 아니라 '같은 인덱스(과목 이름)'끼리 계산된다
#     student2 는 수학, 국어, 영어 순서지만 → 국어는 국어끼리, 수학은 수학끼리 계산됨
addition = student1 + student2               #덧셈
subtraction = student1 - student2            #뺄셈
multiplication = student1 * student2         #곱셈
division = student1 / student2               #나눗셈
print(type(division))                        # 결과도 시리즈 → <class 'pandas.Series'>
print('\n')

<class 'pandas.Series'>

In [75]:
# 사칙연산 결과를 데이터프레임으로 합치기 (시리즈 -> 데이터프레임)
# 시리즈 하나가 행 하나가 되고, 과목 이름이 열 이름이 된다
result = pd.DataFrame([addition, subtraction, multiplication, division],
                      index = ['덧셈','뺄셈','곱셈','나눗셈'])   # 행 이름
result

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

* series to seires2

In [84]:
import pandas as pd
import numpy as np   # np.nan(빈 값)을 쓰기 위해 numpy 불러오기

# 빈 값(NaN)과 짝이 없는 인덱스가 있는 경우
student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})   # 국어 = NaN
student2 = pd.Series({'수학':80, '국어':90})                  # 영어 없음

print(student1)
print('\n')
print(student2)
print('\n')

# NaN 과 연산하거나, 한쪽에만 있는 인덱스(영어)는 결과가 모두 NaN
addition = student1 + student2               #덧셈
subtraction = student1 - student2            #뺄셈
multiplication = student1 * student2         #곱셈
division = student1 / student2               #나눗셈
print(type(division))                        # 결과도 시리즈 → <class 'pandas.Series'>
print('\n')

result = pd.DataFrame([addition, subtraction, multiplication, division],
                      index = ['덧셈','뺄셈','곱셈','나눗셈'])
result   # 국어, 영어 열은 NaN / 수학만 계산됨

국어     NaN
영어    80.0
수학    90.0
dtype: float64


수학    80
국어    90
dtype: int64


<class 'pandas.Series'>

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [86]:
import pandas as pd
import numpy as np

student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90})

print(student1)
print('\n')
print(student2)
print('\n')

# 연산 메소드 + fill_value=0 : 값이 없는 쪽(NaN 또는 짝 없는 인덱스)을 0 으로 보고 계산
sr_add = student1.add(student2, fill_value=0)   # 덧셈 (+)
sr_sub = student1.sub(student2, fill_value=0)   # 뺄셈 (-)
sr_mul = student1.mul(student2, fill_value=0)   # 곱셈 (*)
sr_div = student1.div(student2, fill_value=0) #인피니티 에러(0으로 나눠서) → 영어 80/0 = inf (에러 아님)

result = pd.DataFrame([sr_add,sr_sub,sr_mul,sr_div],
                      index=['덧셈','뺄셈','곱셈','나눗셈'])

result

국어     NaN
영어    80.0
수학    90.0
dtype: float64


수학    80
국어    90
dtype: int64

       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

* df to number

In [89]:
import pandas as pd
import seaborn as sns   # seaborn : 시각화 라이브러리. 연습용 데이터셋도 제공

# 타이타닉 승객 데이터 불러오기 (891행 x 15열, 인터넷 연결 필요)
titanic = sns.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [92]:
# df에 age, fare 추출
df = titanic.loc[:, ['age', 'fare']]   # : = 모든 행, ['age','fare'] = 선택할 열 (나이, 요금)
print(df.head())                              # 앞 5행만 미리보기
print("\n")
print((type(df)))                             # DataFrame

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500


<class 'pandas.DataFrame'>

In [ ]:
#데이터 프레임에 숫자 10 더하기
addition = df + 10   # 모든 칸에 10 이 더해진다 (NaN 은 그대로 NaN)
print(addition.head())
print("\n")
print(type(addition))   # 결과도 DataFrame

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500


<class 'pandas.DataFrame'>

* df to df

In [96]:
#데이터 프레임에 숫자 10 더하기
addition = df + 10
print(addition.tail())   # tail() = 뒤 5행 미리보기
print("\n")
print(type(addition))
print("\n")

#데이터프레임끼리 연산하기(addition - df)
#   같은 행 인덱스 + 같은 열 이름 끼리 계산 → 모든 칸이 10 (age 가 NaN 인 칸은 NaN)
subtraction = addition -df
print(subtraction.tail())
print('\n')
print(type(subtraction))

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75


<class 'pandas.DataFrame'>


      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0


<class 'pandas.DataFrame'>