## 외부 파일 읽어오기

* csv 파일

In [4]:
import pandas as pd   # pandas 를 pd 라는 짧은 이름으로 불러오기

# 읽을 파일 경로 : ./ = 지금 노트북이 있는 폴더(src) → Data-Pandas 폴더 안의 csv 파일
file_path = './Data-Pandas/read_csv_sample.csv'

# read_csv() : CSV 파일 → 데이터프레임
#   header=0 (기본값) : 0번째 줄(첫 줄)을 열 이름으로 사용 → 열 이름 c0, c1, c2, c3
#   행 인덱스는 지정 안 했으니 0, 1, 2 자동 생성
df1 = pd.read_csv(file_path) #header=0
print(df1)

   c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9

In [5]:
# read_csv() 함수로 데이터프레임 변환. 변수 df2에 저장. header=None 옵션
#   header=None : "열 이름 줄이 없다" → 첫 줄(c0, c1 ...)도 데이터로 읽음
#   열 이름은 0, 1, 2, 3 으로 자동 생성 / 숫자와 글자가 섞여 모든 열이 글자(str)가 된다
df2 = pd.read_csv(file_path, header=None)
print(df2)
print('\n')   # '\n' = 줄바꿈 (결과 사이에 빈 줄)

    0   1   2   3
0  c0  c1  c2  c3
1   0   1   4   7
2   1   2   5   8
3   2   3   6   9

In [6]:
# read_csv() 함수로 데이터프레임 변환. 변수 df3에 저장. index_col=None 옵션
#   index_col=None (기본값) : 어떤 열도 행 인덱스로 쓰지 않음 → df1 과 같은 결과

df3 = pd.read_csv(file_path, index_col=None)
print(df3)
print('\n')

   c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9

In [7]:
# index_col = 'c0' 옵션
#   c0 열을 행 인덱스로 사용 (읽으면서 set_index('c0') 를 한 것과 같음)
#   c0 는 이제 열이 아니라 행 이름표 → 열 목록에는 c1, c2, c3 만 남는다
df4 = pd.read_csv(file_path, index_col = 'c0')
print(df4)

    c1  c2  c3
c0
0    1   4   7
1    2   5   8
2    3   6   9

In [8]:
# 남북한발전전력량.xlsx
file_path = './Data-Pandas/남북한발전전력량.xlsx'

# read_excel() : 엑셀 파일 → 데이터프레임 (첫 번째 시트를 읽음)
#   engine='openpyxl' : .xlsx 를 여는 도구 (없으면 pip install openpyxl)
#   엑셀의 병합 셀('남한' 등)은 첫 칸에만 값이 들어가고 나머지는 NaN 으로 나온다
df1 = pd.read_excel(file_path, engine='openpyxl') #header=0 (default옵션)
print(df1)

# header=None : 엑셀 첫 줄(전력량, 발전 전력별, 1990 ...)도 데이터로 읽음 → 열 이름은 0, 1, 2 ...
#   ※ df2 는 만들기만 하고 출력은 안 함 (결과를 보려면 print(df2) 추가)
df2 = pd.read_excel('./Data-Pandas/남북한발전전력량.xlsx',engine='openpyxl',header=None) #header=None 옵션

  전력량 (억㎾h) 발전 전력별  1990  1991  1992  1993  1994  1995  1996  1997  ...  2007  \
0        남한     합계  1077  1186  1310  1444  1650  1847  2055  2244  ...  4031
1       NaN     수력    64    51    49    60    41    55    52    54  ...    50
2       NaN     화력   484   573   696   803  1022  1122  1264  1420  ...  2551
3       NaN    원자력   529   563   565   581   587   670   739   771  ...  1429
4       NaN    신재생     -     -     -     -     -     -     -     -  ...     -
5        북한     합계   277   263   247   221   231   230   213   193  ...   236
6       NaN     수력   156   150   142   133   138   142   125   107  ...   133
7       NaN     화력   121   113   105    88    93    88    88    86  ...   103
8       NaN    원자력     -     -     -     -     -     -     -     -  ...     -

   2008  2009  2010  2011  2012  2013  2014  2015  2016
0  4224  4336  4747  4969  5096  5171  5220  5281  5404
1    56    56    65    78    77    84    78    58    66
2  2658  2802  3196  3343  3430  3581  3427  3402  3523
3  1510  1478  1486  1547  1503  1388  1564  1648  1620
4     -     -     -     -    86   118   151   173   195
5   255   235   237   211   215   221   216   190   239
6   141   125   134   132   135   139   130   100   128
7   114   110   103    79    80    82    86    90   111
8     -     -     -     -     -     -     -     -     -

[9 rows x 29 columns]

* JSON파일
# read_json_sample.json

In [9]:
import pandas as pd

# read_json() : JSON 파일 → 데이터프레임
#   JSON 의 바깥 키(name, year, developer, opensource) → 열 이름
#   안쪽 키(pandas, NumPy, matplotlib)                  → 행 인덱스
df = pd.read_json('./Data-Pandas/read_json_sample.json')
print(df)
print('\n' )
print(df.index)   # 행 인덱스 확인 → ['pandas', 'NumPy', 'matplotlib']

           name  year        developer opensource
pandas           2008    Wes Mckinneye       True
NumPy            2006  Travis Oliphant       True
matplotlib       2003   John D. Hunter       True


Index(['pandas', 'NumPy', 'matplotlib'], dtype='str')

* html파일(web문서)
* ettxnsions -> browser

In [10]:
import pandas as pd

# HTML 파일 경로 (data → Data-Pandas 로 수정)
url = './Data-Pandas/sample.html'

# read_html() : HTML 안의 <table> 태그를 모두 찾아서 '데이터프레임들의 리스트'로 반환
#   lxml 도구가 필요 (없으면 pip install lxml)
tables = pd.read_html(url)

# 표(table)의 개수 확인
print(len(tables))          # 2 → sample.html 안에 표가 2개
print('\n')
print(type(tables))         # <class 'list'> → 결과 전체는 리스트
print(type(tables[0]))      # <class 'pandas.DataFrame'> → 리스트 안의 각 표는 데이터프레임

2


<class 'list'>
<class 'pandas.DataFrame'>

In [11]:
# 리스트 안의 표를 하나씩 꺼내서 출력
for i in range(len(tables)):      # len(tables) = 2 → i = 0, 1
    print("tables[%s]" % i)       # %s 자리에 i 가 들어감 → "tables[0]" (f"tables[{i}]" 와 같음)
    print(tables[i])              # i 번째 표 출력

tables[0]
   Unnamed: 0  c0  c1  c2  c3
0           0   0   1   4   7
1           1   1   2   5   8
2           2   2   3   6   9
tables[1]
         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True

In [12]:
# 두 번째 표(1번)를 꺼내서 df 에 저장
df = tables[1]

# name 열을 행 인덱스로 지정 (inplace=True → df 자체를 변경)
df.set_index(['name'],inplace=True)
print(df)

            year        developer  opensource
name
NumPy       2006  Travis Oliphant        True
matplotlib  2003   John D. Hunter        True
pandas      2008    Wes Mckinneye        True

## 외부파일로 저장하기


* to csv

In [13]:
import pandas as pd

# 저장 실습용 데이터 : 학생별 과목 학점
data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }


df = pd.DataFrame(data)
df.set_index('name', inplace=True)   #name 열을 인덱스로 지정
print(df)

# to_csv() : 데이터프레임 → CSV 파일로 저장 (인덱스 name 도 함께 저장됨)
#   output 폴더가 미리 있어야 한다 / 인덱스를 빼려면 index=False
#   한글이 엑셀에서 깨지면 encoding='utf-8-sig'
df.to_csv("./output/df_sample.csv")

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

* to json("./output/df_sample.json")

In [14]:
# to_json() : 데이터프레임 → JSON 파일로 저장
#   열 이름 → 바깥 키, 행 인덱스(Jerry, Riah, Paul) → 안쪽 키
df.to_json("./output/df_sample.json")

* to excel

In [15]:
# 엑셀 파일로 저장
#   ⚠️ 버그 : to_json 이라서 이름만 .xlsx 이고 내용은 JSON 글자 → 엑셀에서 안 열림
#   올바른 코드 : df.to_excel("./output/df_sample.xlsx")
df.to_json("./output/df_sample.xlsx")

* toi excewriter

In [16]:
import pandas as pd

# 엑셀 시트 2개에 나눠 저장할 데이터 2개
# data1 : 학생별 과목 학점 → sheet1 에 저장할 예정
data1 = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }


# data2 : 숫자 표 → sheet2 에 저장할 예정
data2 = {'c0':[1,2,3],
         'c1':[4,5,6],
         'c2':[7,8,9],
         'c3':[10,11,12],
         'c4':[13,14,15]
        }

In [17]:
# data1 → df1, name 열을 행 인덱스로
df1 = pd.DataFrame(data1)
df1.set_index('name',inplace=True)
print(df1)
print('\n')

# data2 → df2, c0 열을 행 인덱스로
df2 = pd.DataFrame(data2)
df2.set_index('c0',inplace=True)
print(df2)
print('\n')

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+


    c1  c2  c3  c4
c0
1    4   7  10  13
2    5   8  11  14
3    6   9  12  15

In [18]:
# ExcelWriter : 엑셀 파일 하나에 시트 여러 개를 저장할 때 사용
#   (to_excel("파일명") 을 두 번 하면 두 번째가 첫 번째를 덮어써서 시트 1개만 남음)
writer = pd.ExcelWriter("./output/df_excelwriter.xlsx")   # ① 저장할 엑셀 파일 열기
df1.to_excel(writer, sheet_name="sheet1")                  # ② sheet1 에 df1 쓰기
df2.to_excel(writer, sheet_name="sheet2")                  # ③ sheet2 에 df2 쓰기
writer.close()                                             # ④ 저장하고 닫기 (빠뜨리면 파일이 안 생기거나 깨짐)
# 참고 : with pd.ExcelWriter(...) as writer: 로 쓰면 close() 를 자동으로 해 준다

In [19]:
##데이터 분석하기
# ↑ 코드 셀이라 그냥 주석으로 처리됨. 제목으로 보이게 하려면 셀 종류를 Markdown 으로 변경

In [20]:
import pandas as pd

# auto-mpg.csv : 자동차 398대의 연비·엔진·무게 정보
#   첫 줄부터 바로 데이터라서(열 이름 줄 없음) header=None 으로 읽는다
df= pd.read_csv('./Data-Pandas/auto-mpg.csv', header=None)

# 열 이름 직접 붙이기 (0, 1, 2 ... → 의미 있는 이름)
#   mpg=연비, cylinders=실린더 수, displacement=배기량, horsepower=마력, weight=무게,
#   acceleration=가속 성능, model year=출시 연도(70=1970), origin=생산지(1 미국, 2 유럽, 3 일본), name=차 이름
df.columns = ['mpg','cylinders','displacement','horsepower','weight','acceleration','model year','origin','name']


df.head()   # 앞 5행 미리보기 (head(10) 처럼 개수 지정 가능)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [21]:
df.tail()   # 뒤 5행 미리보기

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

In [22]:
# df의 모양과 크기 확인 : (행의 개수, 열의 개수)를 튜플로 반환
print(df.shape)   # (398, 9) → 398행, 9열 / shape 는 괄호 () 없이 씀

(398, 9)

In [23]:
# 데이터 프레임 df의 자료형 확인
#   float64 = 소수, int64 = 정수, str = 글자
#   ※ horsepower 가 str 인 이유 : 마력 칸 6곳에 숫자 대신 '?' 가 있어서 열 전체가 글자로 읽힘
print(df.dtypes)

mpg             float64
cylinders         int64
displacement    float64
horsepower          str
weight          float64
acceleration    float64
model year        int64
origin            int64
name                str
dtype: object

In [24]:
#데이터 프레임 df의 내용 확인
#   행 개수, 열 이름, 빈칸이 아닌 값 개수(Non-Null Count), 자료형을 한 번에 보여줌
#   ※ '?' 는 빈칸이 아니라 글자라서 horsepower 도 398 non-null 로 나온다
#   ※ info() 는 스스로 출력하고 None 을 돌려주므로 print() 로 감싸면 끝에 None 이 찍힘
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    str
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB
None

In [25]:
# describe() : 숫자 열의 통계 요약
#   count=개수, mean=평균, std=표준편차(퍼진 정도), min=최솟값,
#   25%/50%/75% = 작은 순서로 줄 세웠을 때 1/4, 가운데(중앙값), 3/4 지점의 값, max=최댓값
#   ※ horsepower, name 은 글자 열이라 결과에서 빠진다
print(df.describe())

              mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000
mean    23.514573    5.454774    193.425879  2970.424623     15.568090
std      7.815984    1.701004    104.269838   846.841774      2.757689
min      9.000000    3.000000     68.000000  1613.000000      8.000000
25%     17.500000    4.000000    104.250000  2223.750000     13.825000
50%     23.000000    4.000000    148.500000  2803.500000     15.500000
75%     29.000000    8.000000    262.000000  3608.000000     17.175000
max     46.600000    8.000000    455.000000  5140.000000     24.800000

       model year      origin
count  398.000000  398.000000
mean    76.010050    1.572864
std      3.697627    0.802055
min     70.000000    1.000000
25%     73.000000    1.000000
50%     76.000000    1.000000
75%     79.000000    2.000000
max     82.000000    3.000000

In [28]:

# 산술 데이터가 아닌 열에 대한 정보를 포함하고 싶을 경우(문자형)
# horsepower, name열에 대해 unique(고유값 개수) top(최빈값), freq(빈도수)
#     unique(고유값 개수) : 중복값을 제거한 값들
#     top(최빈값) : 가장 많이 등장한 값
#     freq(빈도수) : 최빈값이 등장한 횟수
#   숫자 열은 unique/top/freq 가 NaN, 글자 열은 mean/std 등이 NaN (해당 없음)
print(df.describe(include='all'))   # include='all' = 모든 열 포함

               mpg   cylinders  displacement horsepower       weight  \
count   398.000000  398.000000    398.000000        398   398.000000
unique         NaN         NaN           NaN         94          NaN
top            NaN         NaN           NaN      150.0          NaN
freq           NaN         NaN           NaN         22          NaN
mean     23.514573    5.454774    193.425879        NaN  2970.424623
std       7.815984    1.701004    104.269838        NaN   846.841774
min       9.000000    3.000000     68.000000        NaN  1613.000000
25%      17.500000    4.000000    104.250000        NaN  2223.750000
50%      23.000000    4.000000    148.500000        NaN  2803.500000
75%      29.000000    8.000000    262.000000        NaN  3608.000000
max      46.600000    8.000000    455.000000        NaN  5140.000000

        acceleration  model year      origin        name
count     398.000000  398.000000  398.000000         398
unique           NaN         NaN         NaN         305
top              NaN         NaN         NaN  ford pinto
freq             NaN         NaN         NaN           6
mean       15.568090   76.010050    1.572864         NaN
std         2.757689    3.697627    0.802055         NaN
min         8.000000   70.000000    1.000000         NaN
25%        13.825000   73.000000    1.000000         NaN
50%        15.500000   76.000000    1.000000         NaN
75%        17.175000   79.000000    2.000000         NaN
max        24.800000   82.000000    3.000000         NaN

In [29]:
#데이터 프레임 df의 각 열이 가지고 있는 원소 개수 확인 (빈칸 NaN 은 제외하고 셈)
print(df.count())

#df.count()가 반환하는 객체 타입 출력
print(type(df.count()))   # Series → 인덱스 = 열 이름, 값 = 개수

mpg             398
cylinders       398
displacement    398
horsepower      398
weight          398
acceleration    398
model year      398
origin          398
name            398
dtype: int64
<class 'pandas.Series'>

In [30]:
#데이터프레임.df 의 특정 열이 가지고 있는 고유값 확인
# value_counts() : 값마다 몇 번 나왔는지 세서 많은 순서로 정렬
#   origin → 1(미국) 249대, 3(일본) 79대, 2(유럽) 70대
#   고유값 목록만 보려면 df['origin'].unique()
unique_values = df['origin'].value_counts()
print(unique_values)

origin
1    249
3     79
2     70
Name: count, dtype: int64