## 1.누락 데이터 처리(NaN : Not a Number, numpy.nan)
* 누락데이터가 많으면 데이터 품질 저하, AI 알고리즘이 왜곡되는 현상 생김

* 누락 데이터 확인

In [1]:
import seaborn as sns

# seaborn 내장 타이타닉 데이터셋 불러오기 (891행 x 15열)
df = sns.load_dataset('titanic')

# deck 열의 값별 개수 집계
# dropna=False : NaN 값까지 집계
nan_deck = df['deck'].value_counts(dropna=False)
print(nan_deck)

deck
NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: count, dtype: int64

In [ ]:
# isnull() 메서드로 누락 데이터 찾기
# 누락 데이터면 True, 유효한 데이터가 존재하면 False
print(df.head().isnull())      # head() : 앞 5행만 확인

   survived  pclass    sex    age  sibsp  parch   fare  embarked  class  \
0     False   False  False  False  False  False  False     False  False
1     False   False  False  False  False  False  False     False  False
2     False   False  False  False  False  False  False     False  False
3     False   False  False  False  False  False  False     False  False
4     False   False  False  False  False  False  False     False  False

     who  adult_male   deck  embark_town  alive  alone
0  False       False   True        False  False  False
1  False       False  False        False  False  False
2  False       False   True        False  False  False
3  False       False  False        False  False  False
4  False       False   True        False  False  False

In [3]:
# notnull() 메서드로 누락 데이터 찾기
# 유효한 데이터가 존재하면 True, 누락 데이터면 False
print(df.head().notnull())

   survived  pclass   sex   age  sibsp  parch  fare  embarked  class   who  \
0      True    True  True  True   True   True  True      True   True  True
1      True    True  True  True   True   True  True      True   True  True
2      True    True  True  True   True   True  True      True   True  True
3      True    True  True  True   True   True  True      True   True  True
4      True    True  True  True   True   True  True      True   True  True

   adult_male   deck  embark_town  alive  alone
0        True  False         True   True   True
1        True   True         True   True   True
2        True  False         True   True   True
3        True   True         True   True   True
4        True  False         True   True   True

In [4]:
# isnull() 메서드로 누락 데이터 개수 구하기
# True = 1, False = 0 으로 계산되므로 sum()하면 NaN 개수가 됨
# axis=0 : 행 방향(위->아래)으로 더함 -> 열별 NaN 개수
print(df.head().isnull().sum(axis=0))

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           3
embark_town    0
alive          0
alone          0
dtype: int64

In [9]:
# 전체 데이터의 열별 누락 데이터 개수
df.isnull().sum(axis=0)

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [8]:
import seaborn as sns

df = sns.load_dataset('titanic')
missing_df = df.isnull()        # 전체 데이터를 True(NaN) / False 로 변환

# 열마다 NaN(True) 개수 출력
for col in missing_df.columns:
    missing_count = missing_df[col].value_counts()    # 각 열의 NaN 개수 파악 (True, False 각각의 개수)
    # print(missing_count)

    try:
        print(col, ': ', missing_count[True])   # NaN 값이 있으면 개수를 출력
    except:
        print(col, ': ', 0)                     # NaN 값이 없으면(True가 없어서 KeyError) 0개 출력

# NaN이 아닌 값이 500개 이상인 열을 남김 - deck 열(891개 중 688개의 NaN 값)
# axis=1 : 열 단위로 삭제, thresh=500 : 유효한 값이 500개 미만인 열은 삭제
df_thresh = df.dropna(axis=1, thresh=500)
print(df_thresh.columns)        # deck 열이 삭제된 것 확인

survived :  0
pclass :  0
sex :  0
age :  177
sibsp :  0
parch :  0
fare :  0
embarked :  2
class :  0
who :  0
adult_male :  0
deck :  688
embark_town :  2
alive :  0
alone :  0
Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='str')

In [ ]:
# NaN이 500개 이하인 열만 남기고 싶을 경우
# df.isnull().sum() <= 500 : 열별로 True/False 를 가진 시리즈(mask)
# df.loc[:, mask] : 모든 행, mask가 True인 열만 선택
df.loc[:, df.isnull().sum() <= 500]

In [12]:
# age 열에 나이 데이터가 없는 모든 행을 삭제 - age 열(891개 중 177개의 NaN 값)
# subset=['age'] : NaN을 검사할 열 지정. 여러개의 변수가 올 경우, how='any'에 의해 한개의 변수라도 NaN이면 행을 삭제해라
# how='all'이면 모두 NaN일 경우에만 삭제
# axis=0 : 행 단위로 삭제
df_age = df.dropna(subset=['age'], how='any', axis=0)
df_age.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

* 누락 데이터 치환

In [ ]:
import seaborn as sns

df = sns.load_dataset('titanic')
print(df['age'].head(10))       # 5번 행이 NaN인 것 확인

In [ ]:
# age 열의 NaN값을 다른 나이 데이터의 평균으로 변경
mean_age = df['age'].mean(axis=0)   # age 열의 평균 계산 (NaN 값 제외)
df['age'] = df['age'].fillna(mean_age)      # NaN 자리를 평균값으로 채움

print(df['age'].head(10))       # 5번 행이 평균값(29.699...)으로 바뀐 것 확인

# 중앙값 : median()

'''
대칭적인 분포 : 평균
이상치가 많은 데이터 : 중앙값
소득, 부동산 가격 : 중앙값(대체적으로 한쪽으로 치우친 분포)
센서 측정값 : 평균(오차가 대칭적이고 이상치가 적음)
금융 거래 금액 : 중앙값(큰 거래가 평균을 왜곡할 수 있음)
'''

* 누락 데이터 치환

In [13]:
import seaborn as sns

df = sns.load_dataset('titanic')
print(df['embark_town'][825:830])       # 829번 행이 NaN인 것 확인

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829            NaN
Name: embark_town, dtype: str

In [14]:
# embark_town 열의 NaN값을 승선도시 중에서 가장 많이 출현한 값(최빈값)으로 치환하기
# value_counts() : 값별 개수 (많은 순 정렬), idxmax() : 개수가 가장 큰 값의 인덱스(도시 이름)
most_freq = df['embark_town'].value_counts(dropna=True).idxmax()
print(most_freq)

Southampton

In [15]:
# NaN 자리를 최빈값(Southampton)으로 채움
df['embark_town'] = df['embark_town'].fillna(most_freq)

print(df['embark_town'][825:830])       # 829번 행이 Southampton으로 바뀐 것 확인

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829    Southampton
Name: embark_town, dtype: str

## 2.중복 데이터 제거

In [16]:
import pandas as pd

# 중복 데이터가 있는 데이터프레임 생성 (0행과 1행이 완전히 같음)
df = pd.DataFrame({'c1':['a', 'a', 'b', 'a', 'b'],
                'c2':[1, 1, 1, 2, 2],
                'c3':[1, 1, 2, 2, 2]})
print(df)

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [17]:
# 데이터프레임에서 중복 행을 제거
# 모든 열의 값이 같은 행을 찾아 처음 나온 행만 남기고 삭제 (1행 삭제)
df2 = df.drop_duplicates()
print(df2)

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [18]:
# c2, c3열을 기준으로 중복 행을 제거
# c2, c3 값만 같으면 중복으로 판단 (1행, 4행 삭제)
df3 = df.drop_duplicates(subset=['c2', 'c3'])
print(df3)

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2

## 3.데이터 표준화

#### 3-1.단위 환산

In [ ]:
# 측정 단위를 동일하게 맞추기
    # 마일, 야드, 온스(영미권) -> 미터 , 평, 그램(한국)

'''
UCI 자동차 연비 데이터셋
    mpg(갤런당 마일 : mile per gallon) : kpl(단위 -> 리터당 킬로미터(km/L))
    1마일 = 1.60934km, 1갤런 = 3.78541리터, 1mpg = 0.425km/L
'''

In [19]:
import pandas as pd

# header=None : CSV 첫 줄이 열 이름이 아니라 데이터이므로 열 이름 없이 읽음
df = pd.read_csv("./data/auto-mpg.csv", header=None)

# 열 이름을 지정
df.columns = [
    "mpg",           # 연비 (갤런당 마일)
    "cylinders",     # 실린더 수
    "displacement",  # 배기량
    "horsepower",    # 출력 (마력)
    "weight",        # 차중
    "acceleration",  # 가속능력
    "model year",    # 출시 년도
    "origin",        # 제조국 (1:USA, 2:EU, 3:JAPAN)
    "name",          # 모델명
]

print(df.head(3))

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70
1  15.0          8         350.0      165.0  3693.0          11.5          70
2  18.0          8         318.0      150.0  3436.0          11.0          70

   origin                       name
0       1  chevrolet chevelle malibu
1       1          buick skylark 320
2       1         plymouth satellite

In [20]:
# mpg -> kpl 환산 계수 (1마일 km / 1갤런 L)
mpg_to_kpl = 1.60934 / 3.78541
df["kpl"] = df["mpg"] * mpg_to_kpl      # 새 열 kpl 추가
print(df.head(3))

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70
1  15.0          8         350.0      165.0  3693.0          11.5          70
2  18.0          8         318.0      150.0  3436.0          11.0          70

   origin                       name       kpl
0       1  chevrolet chevelle malibu  7.652571
1       1          buick skylark 320  6.377143
2       1         plymouth satellite  7.652571

In [21]:
# kpl 열을 소수점 둘째 자리까지 반올림
df["kpl"] = df["kpl"].round(2)
print(df.head(3))

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70
1  15.0          8         350.0      165.0  3693.0          11.5          70
2  18.0          8         318.0      150.0  3436.0          11.0          70

   origin                       name   kpl
0       1  chevrolet chevelle malibu  7.65
1       1          buick skylark 320  6.38
2       1         plymouth satellite  7.65

#### 3-2.자료형 변환

In [22]:
# 숫자로 된 문자열 -> 숫자로 변환
import numpy as np
import pandas as pd

df = pd.read_csv("./data/auto-mpg.csv", header=None)
# 열 이름을 지정
df.columns = [
    "mpg",           # 연비 (갤런당 마일)
    "cylinders",     # 실린더 수
    "displacement",  # 배기량
    "horsepower",    # 출력 (마력)
    "weight",        # 차중
    "acceleration",  # 가속능력
    "model year",    # 출시 년도
    "origin",        # 제조국 (1:USA, 2:EU, 3:JAPAN)
    "name",          # 모델명
]

# 열별 자료형 확인 -> horsepower가 숫자가 아닌 문자열(str)
print(df.dtypes)

mpg             float64
cylinders         int64
displacement    float64
horsepower          str
weight          float64
acceleration    float64
model year        int64
origin            int64
name                str
dtype: object

In [23]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [24]:
# horsepower 열의 고유값 확인
# '?' 가 섞여 있어서 열 전체가 문자열로 읽힘
print(df['horsepower'].unique())

<StringArray>
['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0', '225.0',
 '190.0', '170.0', '160.0', '95.00', '97.00', '85.00', '88.00', '46.00',
 '87.00', '90.00', '113.0', '200.0', '210.0', '193.0',     '?', '100.0',
 '105.0', '175.0', '153.0', '180.0', '110.0', '72.00', '86.00', '70.00',
 '76.00', '65.00', '69.00', '60.00', '80.00', '54.00', '208.0', '155.0',
 '112.0', '92.00', '145.0', '137.0', '158.0', '167.0', '94.00', '107.0',
 '230.0', '49.00', '75.00', '91.00', '122.0', '67.00', '83.00', '78.00',
 '52.00', '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
 '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0', '108.0',
 '68.00', '58.00', '149.0', '89.00', '63.00', '48.00', '66.00', '139.0',
 '103.0', '125.0', '133.0', '138.0', '135.0', '142.0', '77.00', '62.00',
 '132.0', '84.00', '64.00', '74.00', '116.0', '82.00']
Length: 94, dtype: str

In [25]:
# 누락 데이터('?') 삭제 
df['horsepower'] = df['horsepower'].replace('?', np.nan)      # '?'을 np.nan으로 변경
df.dropna(subset=['horsepower'], axis=0, inplace=True)   # 누락데이터 행을 삭제
df['horsepower'] = df['horsepower'].astype('float')      # 문자열을 실수형으로 변환

print(df['horsepower'].dtypes)

float64

In [27]:
# origin 열의 고유값 확인 : 카테고리컬 데이터
# 1:'USA', 2:'EU', 3:'JAPAN'

print(df['origin'].unique())
# 딕셔너리 {기존값: 새 값} 으로 숫자를 국가 이름으로 바꿈
df['origin'] = df['origin'].replace({1:'USA', 2:'EU', 3:'JAPAN'})

print(df['origin'].unique())
print(df['origin'].dtypes)      # 문자열로 바뀜

[1 3 2]
['USA' 'JAPAN' 'EU']
object

In [28]:
# origin 열의 문자열 자료형을 범주형으로 변환
# 몇 가지 값만 반복되는 열은 category로 바꾸면 메모리 절약 + 범주로 다루기 쉬움
df['origin'] = df['origin'].astype('category')
print(df['origin'].dtypes)

category

In [29]:
# model year 열의 정수형을 범주형으로 변환
# 숫자지만 크기 비교보다 '분류(연식)' 의미이므로 범주형이 적합
print(df['model year'].sample(3))       # sample(3) : 무작위 3개 행 추출
df['model year'] = df['model year'].astype('category')
print(df['model year'].sample(3))

180    75
307    79
355    81
Name: model year, dtype: int64
41     71
394    82
176    75
Name: model year, dtype: category
Categories (13, int64): [70, 71, 72, 73, ..., 79, 80, 81, 82]

##  4.범주형(카테고리) 데이터 처리

#### 4-1.구간 분할
* 연속 변수를 일정 구간으로 나누고 카테고리컬 데이터(범주형 이산 데이터)로 변환하는 것

In [30]:
import numpy as np
import pandas as pd

df = pd.read_csv("./data/auto-mpg.csv", header=None)
# 열 이름을 지정
df.columns = [
    "mpg",           # 연비 (갤런당 마일)
    "cylinders",     # 실린더 수
    "displacement",  # 배기량
    "horsepower",    # 출력 (마력)
    "weight",        # 차중
    "acceleration",  # 가속능력
    "model year",    # 출시 년도
    "origin",        # 제조국 (1:USA, 2:EU, 3:JAPAN)
    "name",          # 모델명
]

# 누락 데이터('?') 삭제
df['horsepower'] = df['horsepower'].replace('?', np.nan)      # '?'을 np.nan으로 변경
df.dropna(subset=['horsepower'], axis=0, inplace=True)   # 누락데이터 행을 삭제
df['horsepower'] = df['horsepower'].astype('float')      # 문자열을 실수형으로 변환

# horsepower 열의 자료형 확인
print(df['horsepower'].dtypes)

float64

In [31]:
# np.histogram 함수로 3개의 bin으로 나누는 경계 값의 리스트 구하기
# count : 각 구간의 데이터 개수, bin_dividers : 구간 경계값(4개)
# bins=3 : 최소값~최대값을 같은 간격으로 3등분

count, bin_dividers = np.histogram(df['horsepower'], bins=3)
print(bin_dividers)
print(count)

'''
1구간 : 46.<=  horsepower < 107.33333333
2구간 : 107.33333333 <=  horsepower < 168.66666667
3구간 : 168.66666667 <=  horsepower <= 230.
'''

[ 46.         107.33333333 168.66666667 230.        ]
[257 103  32]

In [32]:
# 3개의 bin에 이름 지정
bin_names = ['저출력', '보통출력', '고출력']

# pd.cut() : 연속된 숫자 데이터를 구간별 범주로 나눔
df['hp_bin'] = pd.cut(x=df['horsepower'],     # 데이터 배열
                    bins=bin_dividers,      # 경계 값 리스트
                    labels=bin_names,       # bin 이름
                    include_lowest=True)    # 첫 경계값(46.0)도 1구간에 포함

print(df[['horsepower', 'hp_bin']].head(15))

    horsepower hp_bin
0        130.0   보통출력
1        165.0   보통출력
2        150.0   보통출력
3        150.0   보통출력
4        140.0   보통출력
5        198.0    고출력
6        220.0    고출력
7        215.0    고출력
8        225.0    고출력
9        190.0    고출력
10       170.0    고출력
11       160.0   보통출력
12       150.0   보통출력
13       225.0    고출력
14        95.0    저출력

## 5.정규화(Normalization)
* 0~1, -1~1 까지의 범위를 가지고 있음

In [33]:
import numpy as np
import pandas as pd

# 데이터를 새로 불러옴 (앞 셀에서 df가 바뀌었을 수 있으므로)
df = pd.read_csv("./data/auto-mpg.csv", header=None)
# 열 이름을 지정
df.columns = [
    "mpg",           # 연비 (갤런당 마일)
    "cylinders",     # 실린더 수
    "displacement",  # 배기량
    "horsepower",    # 출력 (마력)
    "weight",        # 차중
    "acceleration",  # 가속능력
    "model year",    # 출시 년도
    "origin",        # 제조국 (1:USA, 2:EU, 3:JAPAN)
    "name",          # 모델명
]

# 누락 데이터('?') 삭제
df['horsepower'] = df['horsepower'].replace('?', np.nan)      # '?'을 np.nan으로 변경
df.dropna(subset=['horsepower'], axis=0, inplace=True)   # 누락데이터 행을 삭제
df['horsepower'] = df['horsepower'].astype('float')      # 문자열을 실수형으로 변환

In [34]:
# 정규화 전 horsepower 통계 확인 (min 46 ~ max 230)
print(df.horsepower.describe())

count    392.000000
mean     104.469388
std       38.491160
min       46.000000
25%       75.000000
50%       93.500000
75%      126.000000
max      230.000000
Name: horsepower, dtype: float64

In [35]:
# 정규화 : 각 열의 값을 그 열의 최대값(절대값)으로 나누어 0 ~ 1 범위로 변환
# 열마다 숫자 크기(단위)가 달라도 같은 범위로 맞춰서 비교 가능하게 함
df.horsepower = df.horsepower / abs(df.horsepower.max()) # abs : 절대값

print(df.horsepower.head())
print('\n')
print(df.horsepower.describe())     # max가 1.0인 것 확인

0    0.565217
1    0.717391
2    0.652174
3    0.652174
4    0.608696
Name: horsepower, dtype: float64


count    392.000000
mean       0.454215
std        0.167353
min        0.200000
25%        0.326087
50%        0.406522
75%        0.547826
max        1.000000
Name: horsepower, dtype: float64

#### 6-1.다른 자료형의 시계열 객체로 변환

* 문자열을 Timestamp로 변환

In [41]:
import pandas as pd

# 주식 데이터 불러오기
df = pd.read_csv('./data/stock-data.csv')

print(df.head())
print('\n')
print(df.info())        # Date 열이 날짜가 아닌 문자열(str)인 것 확인

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039


<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     str
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), str(1)
memory usage: 1.1 KB
None

In [42]:
# 문자열 데이터(시리즈 객체)를 판다스 Timestamp로 변환
df['new_Date'] = pd.to_datetime(df['Date'])     # 새 열 new_Date 추가

print(df.head())
print('\n')
print(df.info())                    # new_Date 열이 datetime64 인 것 확인
print('\n')
print(type(df['new_Date'][0]))      # 원소 하나의 자료형 : Timestamp

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26


<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_Date  20 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.2 KB
None


<class 'pandas.Timestamp'>

In [43]:
# new_Date 열을 행 인덱스로 지정 -> DatetimeIndex (날짜로 행 선택, 기간별 집계 가능)
df.set_index('new_Date', inplace=True)
# 원래 문자열 Date 열은 new_Date와 같은 정보라서 삭제 (axis=1 : 열 삭제)
df.drop('Date', axis=1, inplace=True)

print(df.head())
print('\n')
print(df.info())

            Close  Start   High    Low  Volume
new_Date
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039


<class 'pandas.DataFrame'>
DatetimeIndex: 20 entries, 2018-07-02 to 2018-06-01
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   20 non-null     int64
 1   Start   20 non-null     int64
 2   High    20 non-null     int64
 3   Low     20 non-null     int64
 4   Volume  20 non-null     int64
dtypes: int64(5)
memory usage: 960.0 bytes
None

* Timestamp를 Period로 변환

In [44]:
import pandas as pd

# 날짜 문자열 리스트
dates = ['2019-01-01', '2020-03-01', '2021-06-01']

# 문자열 리스트 -> DatetimeIndex (Timestamp 배열)
ts_dates = pd.to_datetime(dates)
print(ts_dates)

DatetimeIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='datetime64[us]', freq=None)

In [45]:
# Timestamp를 Period로 변환
# Timestamp : 특정 시점 (2019-01-01 00:00:00)
# Period    : 기간 (2019-01 = 2019년 1월 한 달 전체)
pr_day = ts_dates.to_period(freq='D')    # 일
print(pr_day)
pr_month = ts_dates.to_period(freq='M')  # 달
print(pr_month)
pr_year = ts_dates.to_period(freq='Y')   # 년 (Y-DEC : 12월에 끝나는 1년)
print(pr_year)

PeriodIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='period[D]')
PeriodIndex(['2019-01', '2020-03', '2021-06'], dtype='period[M]')
PeriodIndex(['2019', '2020', '2021'], dtype='period[Y-DEC]')

In [46]:
import pandas as pd

# 주식 거래 예시 데이터프레임 생성 (거래일은 아직 문자열)
df = pd.DataFrame({
    '거래일': [
        '2025-01-10', '2025-01-20',
        '2025-02-10', '2025-02-20',
        '2026-01-10', '2026-01-20'
    ],
    '종가': [70000, 72000, 71000, 75000, 80000, 82000],      # 장 마감 가격
    '거래량': [1000, 1500, 1200, 1800, 2000, 2500]          # 거래된 주식 수
})

# 문자열을 Timestamp로 변환
df['거래일'] = pd.to_datetime(df['거래일'])

# 월 단위 Period 생성 -> 새 열 거래월 추가
# .dt : 날짜형 열에서 날짜 관련 기능을 쓰기 위한 접근자
df['거래월'] = df['거래일'].dt.to_period('M')

print(df)

         거래일     종가   거래량      거래월
0 2025-01-10  70000  1000  2025-01
1 2025-01-20  72000  1500  2025-01
2 2025-02-10  71000  1200  2025-02
3 2025-02-20  75000  1800  2025-02
4 2026-01-10  80000  2000  2026-01
5 2026-01-20  82000  2500  2026-01

In [47]:
# 월별 거래량 합계 계산
# groupby('거래월') : 같은 달끼리 묶음 -> ['거래량'].sum() : 묶음별 거래량 합계
monthly = df.groupby('거래월')['거래량'].sum()
print(monthly)

거래월
2025-01    2500
2025-02    3000
2026-01    4500
Freq: M, Name: 거래량, dtype: int64

In [49]:
# 월별 종가와 수익률 계산
# last() : 각 달의 마지막 거래일 종가 = 월말 종가
monthly_close = df.groupby('거래월')['종가'].last()
monthly_close

거래월
2025-01    72000
2025-02    75000
2026-01    82000
Freq: M, Name: 종가, dtype: int64

In [51]:
# 전월 대비 수익률(%)
# pct_change() : (이번 값 - 이전 값) / 이전 값 -> 첫 달은 비교 대상이 없어서 NaN
monthly_return = monthly_close.pct_change() * 100

print("\n월별 수익률(%):")
print(monthly_return.round(2))      # 소수점 둘째 자리까지 반올림

# (75000 - 72000) / 72000  = 0.041667 : 이전달 종가 대비 변화율 소수로 반환

월별 수익률(%):
거래월
2025-01     NaN
2025-02    4.17
2026-01    9.33
Freq: M, Name: 종가, dtype: float64

#### 6-2.시계열 데이터 만들기

* Timestamp 배열

In [52]:
import pandas as pd

# Timestamp의 배열 만들기 - 월 간격, 월의 시작일 기준
ts_ms = pd.date_range(start='2019-01-01',    # 날짜 범위의 시작
                end=None,                 # 날짜 범위의 끝
                periods=6,                # 생성할 Timestamp의 개수
                freq='MS',                # 시간 간격 (MS: 월의 시작일)
                tz='Asia/Seoul')          # 시간대(timezone)
print(ts_ms)

DatetimeIndex(['2019-01-01 00:00:00+09:00', '2019-02-01 00:00:00+09:00',
               '2019-03-01 00:00:00+09:00', '2019-04-01 00:00:00+09:00',
               '2019-05-01 00:00:00+09:00', '2019-06-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='MS')

In [53]:
ts_me = pd.date_range(start='2019-01-01',    # 날짜 범위의 시작
                end=None,                 # 날짜 범위의 끝
                periods=6,                # 생성할 Timestamp의 개수
                freq='ME',                # 시간 간격 (ME: 월의 마지막)
                tz='Asia/Seoul')          # 시간대(timezone)

print(ts_me)

DatetimeIndex(['2019-01-31 00:00:00+09:00', '2019-02-28 00:00:00+09:00',
               '2019-03-31 00:00:00+09:00', '2019-04-30 00:00:00+09:00',
               '2019-05-31 00:00:00+09:00', '2019-06-30 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='ME')

In [54]:
ts_3m = pd.date_range(start='2019-01-01',    # 날짜 범위의 시작
                end=None,                 # 날짜 범위의 끝
                periods=6,                # 생성할 Timestamp의 개수
                freq='3ME',                # 시간 간격 (3ME: 3개월)
                tz='Asia/Seoul')          # 시간대(timezone)

print(ts_3m)

DatetimeIndex(['2019-01-31 00:00:00+09:00', '2019-04-30 00:00:00+09:00',
               '2019-07-31 00:00:00+09:00', '2019-10-31 00:00:00+09:00',
               '2020-01-31 00:00:00+09:00', '2020-04-30 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='3ME')

* Period 배열

In [55]:
import pandas as pd

# 1개월 길이
pr_m = pd.period_range(start='2019-01-01',  # 날짜 범위의 시작
                end=None,                   # 날짜 범위의 끝
                periods=3,                  # 생성할 Period 개수
                freq='M')                   # 기간의 길이 (M: 월)
print(pr_m)

PeriodIndex(['2019-01', '2019-02', '2019-03'], dtype='period[M]')

In [ ]:
# 1시간 길이
pr_h = pd.period_range(start='2019-01-01',  # 날짜 범위의 시작
                end=None,                   # 날짜 범위의 끝
                periods=3,                  # 생성할 Period 개수
                freq='h')                   # 기간의 길이 (h:시간)
print(pr_h)

PeriodIndex(['2019-01-01 00:00', '2019-01-01 01:00', '2019-01-01 02:00'], dtype='period[h]')

In [57]:
# 2시간 길이
pr_2h = pd.period_range(start='2019-01-01',  # 날짜 범위의 시작
                end=None,                   # 날짜 범위의 끝
                periods=3,                  # 생성할 Period 개수
                freq='2h')                   # 기간의 길이 (2h:2시간)
print(pr_2h)

PeriodIndex(['2019-01-01 00:00', '2019-01-01 02:00', '2019-01-01 04:00'], dtype='period[2h]')

#### 6-3.시계열 데이터 활용

* 날짜 데이터 분리

In [58]:
import pandas as pd

df = pd.read_csv('./data/stock-data.csv')
df['new_Date'] = pd.to_datetime(df['Date'])     # 문자열 -> Timestamp(날짜형)
print(df.head())

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [59]:
# .dt : 날짜형 열에서 연/월/일을 꺼내는 접근자
df['Year'] = df['new_Date'].dt.year      # 연
df['Month'] = df['new_Date'].dt.month    # 월
df['Day'] = df['new_Date'].dt.day        # 일
print(df.head())

         Date  Close  Start   High    Low  Volume   new_Date  Year  Month  Day
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02  2018      7    2
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29  2018      6   29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28  2018      6   28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27  2018      6   27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26  2018      6   26

* 인덱싱

In [60]:
import pandas as pd

# 데이터를 새로 불러옴 (앞에서 Year, Month, Day 열을 추가했으므로)
df = pd.read_csv('./data/stock-data.csv')
df['new_Date'] = pd.to_datetime(df['Date'])     # 문자열 -> Timestamp(날짜형)
print(df.head())

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [61]:
# new_Date 열을 인덱스로 지정 -> 날짜로 행 선택 가능 (한 번만 실행할 것)
df.set_index('new_Date', inplace=True)
# 날짜 오름차순 정렬 (원본은 최신 날짜부터 거꾸로 정렬되어 있음)
# 날짜 범위 슬라이싱(:)은 인덱스가 오름차순이어야 동작함
df.sort_index(inplace=True)
print(df.head())

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-08  2018-06-08  11950  11950  12200  11800   59258

In [62]:
# 날짜 인덱스를 이용하여 데이터 선택 - 2018
# 연도만 써도 해당 연도의 모든 행 선택 (부분 문자열 인덱싱)
df_y = df.loc['2018']
print(df_y.head())

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-08  2018-06-08  11950  11950  12200  11800   59258

In [63]:
# 2018-07 : 2018년 7월의 모든 행 선택
df_ym = df.loc['2018-07']
print(df_ym)

                  Date  Close  Start   High    Low  Volume
new_Date
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [64]:
# 2018-07, start, high
# df.loc[행, 열] : 2018년 7월 행 중에서 Start 열부터 High 열까지 선택
df_ym_cols = df.loc['2018-07', 'Start':'High']
print(df_ym_cols)

            Start   High
new_Date
2018-07-02  10850  10900

In [65]:
# 2018-07-02 : 특정 날짜 하루의 데이터 선택
df_ymd = df.loc['2018-07-02']
print(df_ymd)

Date      2018-07-02
Close          10100
Start          10850
High           10900
Low            10000
Volume        137977
Name: 2018-07-02 00:00:00, dtype: object

In [68]:
# 2018-06-08~2018-06-20
# 시작:끝 날짜 범위 지정 (끝 날짜도 포함)
df_ymd_range = df.loc['2018-06-08':'2018-06-20']    # 날짜 범위 지정
print(df_ymd_range)

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-08  2018-06-08  11950  11950  12200  11800   59258
2018-06-11  2018-06-11  11950  12000  12250  11950   62293
2018-06-12  2018-06-12  13200  12200  13300  12050  558148
2018-06-14  2018-06-14  13450  13200  13700  13150  347451
2018-06-15  2018-06-15  13400  13600  13600  12900  201376
2018-06-18  2018-06-18  12000  13400  13400  12000  309787
2018-06-19  2018-06-19  11300  11850  11950  11300  180656
2018-06-20  2018-06-20  11550  11200  11600  10900  308596

In [67]:
# 전체 데이터 확인
df

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-08  2018-06-08  11950  11950  12200  11800   59258
2018-06-11  2018-06-11  11950  12000  12250  11950   62293
2018-06-12  2018-06-12  13200  12200  13300  12050  558148
2018-06-14  2018-06-14  13450  13200  13700  13150  347451
2018-06-15  2018-06-15  13400  13600  13600  12900  201376
2018-06-18  2018-06-18  12000  13400  13400  12000  309787
2018-06-19  2018-06-19  11300  11850  11950  11300  180656
2018-06-20  2018-06-20  11550  11200  11600  10900  308596
2018-06-21  2018-06-21  11200  11350  11750  11200  133002
2018-06-22  2018-06-22  11300  11250  11450  10750  134805
2018-06-25  2018-06-25  11150  11400  11450  11000   55519
2018-06-26  2018-06-26  10800  10900  11000  10700   63039
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977