In [72]:
''' 
1.함수 매핑
    1-1.개별 원소에 함수 매핑
        * 시리즈 원소에 함수 매핑
        * 데이터프레임 원소에 함수 매핑
    1-2.시리즈 객체에 함수 매핑
        * 데이터프레임의 각 열에 함수 매핑
            ** 리턴값이 시리즈
            ** 리턴값이 원소
        * 데이터프레임의 각 행에 함수 매핑
    1-3.데이터프레임 객체에 함수 매핑
'''

' \n1.함수 매핑\n    1-1.개별 원소에 함수 매핑\n        * 시리즈 원소에 함수 매핑\n        * 데이터프레임 원소에 함수 매핑\n    1-2.시리즈 객체에 함수 매핑\n        * 데이터프레임의 각 열에 함수 매핑\n            ** 리턴값이 시리즈\n            ** 리턴값이 원소\n        * 데이터프레임의 각 행에 함수 매핑\n    1-3.데이터프레임 객체에 함수 매핑\n'

## 1.함수 매핑

#### 1-1.개별 원소에 함수 매핑

* 시리즈 원소에 함수 매핑

In [73]:
import seaborn as sns

titanic = sns.load_dataset('titanic')     # seaborn 내장 타이타닉 데이터 (891행)
df = titanic.loc[:, ['age','fare']]       # 나이, 요금 열만 선택
df['ten'] = 10                            # 모든 행에 10을 넣은 열 추가 (행 연산 실습용)
print(df.head())

    age     fare  ten
0  22.0   7.2500   10
1  38.0  71.2833   10
2  26.0   7.9250   10
3  35.0  53.1000   10
4  35.0   8.0500   10

In [74]:
# 사용자 함수 정의
def add_10(n):   # 10을 더하는 함수 (값 1개 → 값 1개)
    return n + 10

def add_two_obj(a, b):    # 두 객체의 합 (인자 2개)
    return a + b

In [75]:
# 데이터에 적용하기 전에 함수가 제대로 동작하는지 먼저 확인
print(add_10(10))            # 20
print(add_two_obj(10, 10))   # 20

20
20

In [76]:
# 시리즈 객체에 적용
# age 열의 값을 하나씩 add_10에 넣고, 결과를 모아 새 시리즈로 반환
# 함수 이름만 전달 (add_10() 처럼 괄호 붙이면 안 됨)
sr1 = df['age'].apply(add_10)
print(sr1.head())

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [77]:
# # test code : 값이 하나씩 들어오는지 print로 확인 (891번 찍힘)
# def add_10(n):
#     print("처리중:", n)
#     return n + 10

# df['age'].apply(add_10)

In [78]:
# 시리즈 객체와 숫자에 적용 : 2개의 인수(시리즈 + 숫자)
# 첫 번째 인자 a 에는 시리즈 값이 자동으로 들어가고, 나머지 b 는 키워드로 따로 전달
sr2 = df['age'].apply(add_two_obj, b=10)
print(sr2.head())

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [79]:
# 람다 함수 활용: 시리즈 객체에 적용
# sr3 = df['age'].apply(lambda x: add_10(x))    # sr1 과 같은 결과
# 나이가 짝수면 10을 더하고, 홀수면 그대로 (NaN 은 조건이 False → 그대로 NaN)
sr3 = df['age'].apply(lambda x: add_10(x) if x % 2 == 0 else x)
print(sr3.head())

0    32.0
1    48.0
2    36.0
3    35.0
4    35.0
Name: age, dtype: float64

* 데이터프레임 원소에 함수 매핑

In [80]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]     # 숫자 열 2개만 (글자 열이 있으면 +10 에서 에러)

print(df.head())

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [81]:
def add_10(n):   # 10을 더하는 함수
    return n + 10

In [82]:
# 데이터프레임의 모든 칸(원소)에 함수 적용 → 같은 모양의 데이터프레임 반환
# (예전 버전의 applymap() 이 map() 으로 이름이 바뀜)
df_map = df.map(add_10)
print(df_map.head())

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

* 금융 sample

In [83]:
import pandas as pd

# 금융 예제용 데이터프레임 (종목 4개)
df = pd.DataFrame({
    '종목': ['삼성전자', 'SK하이닉스', '현대차', '카카오'],
    '종가': [70000, 180000, 250000, 55000],
    '수익률(%)': [2.5, -1.2, 3.8, -0.5],
    '거래량': [1000000, 800000, 450000, 1200000]
})

print(df)

       종목      종가  수익률(%)      거래량
0    삼성전자   70000     2.5  1000000
1  SK하이닉스  180000    -1.2   800000
2     현대차  250000     3.8   450000
3     카카오   55000    -0.5  1200000

** 시리즈 원소에 함수 매핑

In [84]:
# 예제 1. 종가에 10% 목표 수익률 적용
def target_price(price):     # 종가 1개를 받아서
    return price * 1.10      # 10% 올린 값 반환

# 종가 시리즈에 함수 매핑 : '목표가' 변수명 추가
df['목표가'] = df['종가'].apply(target_price)
# df['목표가'] = df['종가'].map(target_price)    # 시리즈는 map 으로도 같은 결과
# 참고) 단순 계산은 df['종가'] * 1.1 이 더 빠름
df.head()

       종목      종가  수익률(%)      거래량       목표가
0    삼성전자   70000     2.5  1000000   77000.0
1  SK하이닉스  180000    -1.2   800000  198000.0
2     현대차  250000     3.8   450000  275000.0
3     카카오   55000    -0.5  1200000   60500.0

In [85]:
# 예제 2. 수익률에 따라 매수·매도 신호 만들기
# if/elif 처럼 조건이 여러 개면 연산자로는 안 되니까 함수 + apply 가 편함
def trading_signal(rate):
    if rate >= 3:            # 3% 이상
        return '강한 상승'
    elif rate > 0:           # 0 초과 ~ 3% 미만
        return '상승'
    elif rate <= -1:         # -1% 이하
        return '하락'
    else:                    # -1% 초과 ~ 0% 이하
        return '약보합'

df['시장신호'] = df['수익률(%)'].apply(trading_signal)    # 숫자 → 글자 라벨
df.head()

       종목      종가  수익률(%)      거래량       목표가   시장신호
0    삼성전자   70000     2.5  1000000   77000.0     상승
1  SK하이닉스  180000    -1.2   800000  198000.0     하락
2     현대차  250000     3.8   450000  275000.0  강한 상승
3     카카오   55000    -0.5  1200000   60500.0    약보합

In [86]:
# 예제 3. 종가가 100,000원 이상이면 목표가 계산, 미만이면 0

# 목표가 계산 함수: 종가 대비 10% 상승
def target_price(price):
    return price * 1.10

# lambda 안에서 조건 분기 : 참이면 target_price(x), 거짓이면 0
df['목표가'] = df['종가'].apply(
    lambda x: target_price(x) if x >= 100000 else 0
)

df.head()

       종목      종가  수익률(%)      거래량       목표가   시장신호
0    삼성전자   70000     2.5  1000000       0.0     상승
1  SK하이닉스  180000    -1.2   800000  198000.0     하락
2     현대차  250000     3.8   450000  275000.0  강한 상승
3     카카오   55000    -0.5  1200000       0.0    약보합

** 데이터프레임 원소에 함수 매핑

In [87]:
# 요일별 종가 (행 인덱스 = 요일, 열 = 종목)
prices = pd.DataFrame({
    '삼성전자': [70000, 71000, 72000],
    'SK하이닉스': [180000, 182000, 185000]
}, index=['월요일', '화요일', '수요일'])

In [88]:
# 예제 4. 금융 수치 전체를 천 원 단위로 변환
def to_thousand(x):
    return x / 1000

result = prices.map(to_thousand)    # 모든 칸에 적용 (prices / 1000 과 같은 결과)
result

     삼성전자  SK하이닉스
월요일  70.0   180.0
화요일  71.0   182.0
수요일  72.0   185.0

In [89]:
# 예제 5. 데이터프레임의 숫자를 등급으로 변환
scores = pd.DataFrame({
    '삼성전자': [90, 65, 30],
    'SK하이닉스': [75, 95, 45]
}, index=['상승점수', '안정점수', '위험점수'])

def grade(score):        # 점수 1개 → 등급 글자 1개
    if score >= 80:
        return 'A'
    elif score >= 60:
        return 'B'
    else:
        return 'C'

result = scores.map(grade)    # 표 전체의 숫자를 등급으로 바꿈
result

     삼성전자 SK하이닉스
상승점수    A      B
안정점수    B      A
위험점수    C      C

#### 1-2.시리즈 객체에 함수 매핑

* 데이터프레임의 각 열에 함수 매핑

** 리턴값이 시리즈

In [90]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]

print(df.head())

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [91]:
# 사용자 함수 정의
def missing_value(series):    # 시리즈를 인수로 전달
    return series.isnull()    # 불린(Boolean) 시리즈를 반환

# 데이터프레임의 각 열을 인수로 전달하면 데이터프레임을 반환
# axis=0 : 열 하나씩(age 1번, fare 1번) 함수에 들어감
result = df.apply(missing_value, axis=0)
print(result.head())
print('\n')
print(type(result))

     age   fare
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False


<class 'pandas.DataFrame'>

** 리턴값이 원소

In [92]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]

print(df.head())

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [93]:
def min_max(x):                  # x = 열 하나(시리즈)
    return x.max() - x.min()     # 최대 - 최소 = 범위 (값 1개)

# 데이터프레임의 각 열을(시리즈) 인수로 전달하면 시리즈를 반환
# 열마다 값 1개씩 → 모으면 시리즈 (age 79.58, fare 512.33)
result = df.apply(min_max)   #기본값 axis=0
print(result)
print('\n')
print(type(result))

age      79.5800
fare    512.3292
dtype: float64


<class 'pandas.Series'>

* 데이터프레임의 각 행에 함수 매핑

In [94]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]
df['ten'] = 10       # 행 연산에 쓸 열
print(df.head())

    age     fare  ten
0  22.0   7.2500   10
1  38.0  71.2833   10
2  26.0   7.9250   10
3  35.0  53.1000   10
4  35.0   8.0500   10

In [95]:
def add_two_obj(a, b):
    return a + b

# axis=1 : 행 하나씩 x 로 들어옴 → x['age'], x['ten'] 으로 그 행의 값을 꺼냄
# 여러 열을 같이 봐야 할 때 사용 (891번 실행이라 느림. 단순 덧셈은 df['age'] + df['ten'] 이 빠름)
df['add'] = df.apply(lambda x: add_two_obj(x['age'], x['ten']), axis=1)   # 행 연산
print(df.head())

    age     fare  ten   add
0  22.0   7.2500   10  32.0
1  38.0  71.2833   10  48.0
2  26.0   7.9250   10  36.0
3  35.0  53.1000   10  45.0
4  35.0   8.0500   10  45.0

#### 1-3.데이터프레임 객체에 함수 매핑

In [96]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]
print(df.head())

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [97]:
# 각 열의 NaN 찾기 - 데이터프레임 전달하면 데이터프레임을 반환
def missing_value(x):
    return x.isnull()

# 각 열의 NaN 개수 반환 - 데이터프레임 전달하면 시리즈 반환
def missing_count(x):    # True=1, False=0 으로 더해져서 개수가 됨
    return missing_value(x).sum()

# 데이터프레임의 총 NaN 개수 - 데이터프레임 전달하면 값을 반환
def total_number_missing(x):
    return missing_count(x).sum()

# pipe : 데이터프레임 전체를 함수에 한 번 넣음 → df.pipe(f) == f(df)
# 리턴 타입은 함수가 뭘 반환하느냐에 따라 달라짐
result_df = df.pipe(missing_value)
print(result_df.head())
print(type(result_df))

     age   fare
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False
<class 'pandas.DataFrame'>

In [98]:
# 열별 NaN 개수 → 시리즈 (age 177, fare 0)
result_series = df.pipe(missing_count)
print(result_series)
print(type(result_series))

age     177
fare      0
dtype: int64
<class 'pandas.Series'>

In [99]:
# 전체 NaN 개수 → 숫자 1개 (177)
result_value = df.pipe(total_number_missing)
print(result_value)
print(type(result_value))

177
<class 'numpy.int64'>

## 2. 열 재구성

#### 2-1.열 순서 변경

In [100]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[0:4, 'survived':'age']    # 0~4행, survived~age 열 (loc 은 끝 포함)
df.head()

   survived  pclass     sex   age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0

In [101]:
df.columns            # 열 이름 (Index 객체)

Index(['survived', 'pclass', 'sex', 'age'], dtype='str')

In [102]:
df.columns.values     # 열 이름 (배열)

<StringArray>
['survived', 'pclass', 'sex', 'age']
Length: 4, dtype: str

In [103]:
# 둘 다 list() 로 감싸면 파이썬 리스트가 됨 → 정렬 등 다루기 편함
list(df.columns), list(df.columns.values)

(['survived', 'pclass', 'sex', 'age'], ['survived', 'pclass', 'sex', 'age'])

In [104]:
# 열 이름의 리스트 만들기
columns = list(df.columns.values)

# 열 이름을 알파벳 순으로 정렬하기
columns_sorted = sorted(columns)
df_sorted = df[columns_sorted]     # df[열이름 리스트] → 리스트 순서대로 열이 나옴
df_sorted

    age  pclass     sex  survived
0  22.0       3    male         0
1  38.0       1  female         1
2  26.0       3  female         1
3  35.0       1  female         1
4  35.0       3    male         0

In [105]:
# 열 이름을 역순으로 정렬
# reversed() 는 리스트가 아니라서 list() 로 감싸야 함
columns_reversed = list(reversed(columns_sorted))
df_reversed = df[columns_reversed]
df_reversed

   survived     sex  pclass   age
0         0    male       3  22.0
1         1  female       1  38.0
2         1  female       3  26.0
3         1  female       1  35.0
4         0    male       3  35.0

#### 2-2.열 분리

In [106]:
import pandas as pd

# 주의) 내 폴더에는 ./data/ 에 파일이 있음
df = pd.read_excel('./data/주가데이터.xlsx', engine= 'openpyxl')
print(df.head(), '\n')
print(df.dtypes, '\n')      # 연월일 열이 datetime64 (날짜 타입)

         연월일   당일종가  전일종가     시가     고가     저가     거래량
0 2018-07-02  10100   600  10850  10900  10000  137977
1 2018-06-29  10700   300  10550  10900   9990  170253
2 2018-06-28  10400   500  10900  10950  10150  155769
3 2018-06-27  10900   100  10800  11050  10500  133548
4 2018-06-26  10800   350  10900  11000  10700   63039

연월일     datetime64[us]
당일종가             int64
전일종가             int64
시가               int64
고가               int64
저가               int64
거래량              int64
dtype: object

In [107]:
df['연월일'] = df['연월일'].astype('str')     # 날짜 → 글자 '2018-07-02'
dates = df['연월일'].str.split('-')           # '-' 기준으로 쪼개기 → ['2018', '07', '02'] 리스트
print(dates.head(), '\n')

0    [2018, 07, 02]
1    [2018, 06, 29]
2    [2018, 06, 28]
3    [2018, 06, 27]
4    [2018, 06, 26]
Name: 연월일, dtype: object

In [108]:
# 리스트에서 n번째 값 꺼내기 (결과는 글자 → 계산하려면 astype(int) 필요)
# 참고) 날짜 타입이면 df['연월일'].dt.year 로도 바로 꺼낼 수 있음
df['연'] = dates.str.get(0)
df['월'] = dates.str.get(1)
df['일'] = dates.str.get(2)
df.head()

          연월일   당일종가  전일종가     시가     고가     저가     거래량     연   월   일
0  2018-07-02  10100   600  10850  10900  10000  137977  2018  07  02
1  2018-06-29  10700   300  10550  10900   9990  170253  2018  06  29
2  2018-06-28  10400   500  10900  10950  10150  155769  2018  06  28
3  2018-06-27  10900   100  10800  11050  10500  133548  2018  06  27
4  2018-06-26  10800   350  10900  11000  10700   63039  2018  06  26

## 3.필터링

#### 3-1.불린 인덱싱

In [109]:
import seaborn as sns

titanic = sns.load_dataset('titanic')

# 나이가 10대(10~19세)인 승객만 따로 선택
# 조건마다 괄호 필수, 그리고 = &  (and 쓰면 에러)
mask1 = (titanic.age >= 10) & (titanic.age < 20)
df_teenage = titanic.loc[mask1, :]       # True 인 행만, 열은 전부
df_teenage.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False

In [110]:
# 나이가 10세 미만(0~9세)이고 여성인 승객만 따로 선택
mask2 = (titanic.age < 10) & (titanic.sex == 'female')
df_female_under10 = titanic.loc[mask2, :]
print(df_female_under10.head())

     survived  pclass     sex  age  sibsp  parch     fare embarked   class  \
10          1       3  female  4.0      1      1  16.7000        S   Third
24          0       3  female  8.0      3      1  21.0750        S   Third
43          1       2  female  3.0      1      2  41.5792        C  Second
58          1       2  female  5.0      1      2  27.7500        S  Second
119         0       3  female  2.0      4      2  31.2750        S   Third

       who  adult_male deck  embark_town alive  alone
10   child       False    G  Southampton   yes  False
24   child       False  NaN  Southampton    no  False
43   child       False  NaN    Cherbourg   yes  False
58   child       False  NaN  Southampton   yes  False
119  child       False  NaN  Southampton    no  False

In [111]:
# 나이가 10세 미만(0~9세) 또는 60세 이상인 승객의 age, sex, alone 열만 선택
# 또는 = |  , loc[행 조건, 열 리스트] 로 행/열을 한 번에 선택
mask3 = (titanic.age < 10)  |(titanic.age >= 60)
df_under10_morethan60 = titanic.loc[mask3, ['age', 'sex', 'alone']]
print(df_under10_morethan60.head())

     age     sex  alone
7    2.0    male  False
10   4.0  female  False
16   2.0    male  False
24   8.0  female  False
33  66.0    male   True

#### 3-2.isin() 메소드 활용

In [112]:
import seaborn as sns
import pandas as pd

titanic = sns.load_dataset('titanic')

# 함께 탑승한 형제 또는 배우자의 수가 3, 4, 5인 승객만 따로 추출 - 불린 인덱싱
# 값마다 조건을 따로 만들어서 | 로 연결 → 값이 많아지면 길어짐
mask3 = titanic['sibsp'] == 3
mask4 = titanic['sibsp'] == 4
mask5 = titanic['sibsp'] == 5
df_boolean = titanic[mask3 | mask4 | mask5]
print(df_boolean.head())

    survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
7          0       3    male   2.0      3      1   21.0750        S  Third
16         0       3    male   2.0      4      1   29.1250        Q  Third
24         0       3  female   8.0      3      1   21.0750        S  Third
27         0       1    male  19.0      3      2  263.0000        S  First
50         0       3    male   7.0      4      1   39.6875        S  Third

      who  adult_male deck  embark_town alive  alone
7   child       False  NaN  Southampton    no  False
16  child       False  NaN   Queenstown    no  False
24  child       False  NaN  Southampton    no  False
27    man        True    C  Southampton    no  False
50  child       False  NaN  Southampton    no  False

In [113]:
# isin() : 리스트 안의 값 중 하나라도 해당되면 True → 위와 같은 결과를 한 줄로
# 반대(목록에 없는 것)는 ~titanic['sibsp'].isin([3, 4, 5])
isin_filter = titanic['sibsp'].isin([3, 4, 5])
df_isin = titanic[isin_filter]
print(df_isin.head())

    survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
7          0       3    male   2.0      3      1   21.0750        S  Third
16         0       3    male   2.0      4      1   29.1250        Q  Third
24         0       3  female   8.0      3      1   21.0750        S  Third
27         0       1    male  19.0      3      2  263.0000        S  First
50         0       3    male   7.0      4      1   39.6875        S  Third

      who  adult_male deck  embark_town alive  alone
7   child       False  NaN  Southampton    no  False
16  child       False  NaN   Queenstown    no  False
24  child       False  NaN  Southampton    no  False
27    man        True    C  Southampton    no  False
50  child       False  NaN  Southampton    no  False

#### 4-1.데이터프레임 연결(concat)
* 기존 데이터프레임의 형태를 유지하면서 이어 붙이는 형태

In [114]:
import pandas as pd

# 데이터프레임 만들기
# df1 : 인덱스 0~3, 열 a b c  /  df2 : 인덱스 2~5, 열 a b c d  → 인덱스 2, 3 이 겹침
df1 = pd.DataFrame({'a': ['a0', 'a1', 'a2', 'a3'],
                    'b': ['b0', 'b1', 'b2', 'b3'],
                    'c': ['c0', 'c1', 'c2', 'c3']},
                    index=[0, 1, 2, 3])

df2 = pd.DataFrame({'a': ['a2', 'a3', 'a4', 'a5'],
                    'b': ['b2', 'b3', 'b4', 'b5'],
                    'c': ['c2', 'c3', 'c4', 'c5'],
                    'd': ['d2', 'd3', 'd4', 'd5']},
                    index=[2, 3, 4, 5])

print(df1, '\n')
print(df2, '\n')

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3

    a   b   c   d
2  a2  b2  c2  d2
3  a3  b3  c3  d3
4  a4  b4  c4  d4
5  a5  b5  c5  d5

In [115]:
# 2개의 데이터프레임을 위 아래 행 방향으로 이어 붙이듯 연결
# df1 에 없는 d 열은 NaN, 인덱스 2, 3 이 중복으로 생김
result1 = pd.concat([df1, df2])
print(result1, '\n')

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
2  a2  b2  c2   d2
3  a3  b3  c3   d3
4  a4  b4  c4   d4
5  a5  b5  c5   d5

In [116]:
# ignore_index=True : index 재 넘버링함 (0 ~ 7)
result2 = pd.concat([df1, df2], ignore_index=True)  # axis = 0 : 행방향
print(result2, '\n')

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
4  a2  b2  c2   d2
5  a3  b3  c3   d3
6  a4  b4  c4   d4
7  a5  b5  c5   d5

In [117]:
# 2개의 데이터프레임을 좌우 열 방향으로 이어 붙이듯 연결하기
# 합집합 : 행 인덱스 기준으로 줄을 맞추고, 없는 곳은 NaN
# 열 이름이 같아도(a, b, c) 합치지 않고 둘 다 남음
result3 = pd.concat([df1, df2], axis=1)  # join='outer'
print(result3, '\n')

     a    b    c    a    b    c    d
0   a0   b0   c0  NaN  NaN  NaN  NaN
1   a1   b1   c1  NaN  NaN  NaN  NaN
2   a2   b2   c2   a2   b2   c2   d2
3   a3   b3   c3   a3   b3   c3   d3
4  NaN  NaN  NaN   a4   b4   c4   d4
5  NaN  NaN  NaN   a5   b5   c5   d5

In [118]:
# join='inner' 옵션 적용하기(교집합) → 양쪽에 다 있는 인덱스 2, 3 만 남음
result3_in = pd.concat([df1, df2], axis=1, join='inner')
print(result3_in, '\n')

    a   b   c   a   b   c   d
2  a2  b2  c2  a2  b2  c2  d2
3  a3  b3  c3  a3  b3  c3  d3

In [119]:
# 시리즈 만들기 (name 이 나중에 열 이름이 됨)
sr1 = pd.Series(['e0', 'e1', 'e2', 'e3'], name='e')                 # 인덱스 0~3
sr2 = pd.Series(['f0', 'f1', 'f2'], name='f', index=[3, 4, 5])      # 인덱스 3~5
sr3 = pd.Series(['g0', 'g1', 'g2', 'g3'], name='g')                 # 인덱스 0~3

print(sr1)
print(sr2)
print(sr3)

0    e0
1    e1
2    e2
3    e3
Name: e, dtype: str
3    f0
4    f1
5    f2
Name: f, dtype: str
0    g0
1    g1
2    g2
3    g3
Name: g, dtype: str

In [120]:
# df1과 sr1을 좌우 열 방향으로 연결 → e 열이 추가됨 (인덱스 0~3 으로 같아서 NaN 없음)
result4 = pd.concat([df1, sr1], axis=1)
print(result4, '\n')

    a   b   c   e
0  a0  b0  c0  e0
1  a1  b1  c1  e1
2  a2  b2  c2  e2
3  a3  b3  c3  e3

In [121]:
# df2과 sr1을 좌우 열 방향으로 연결
# 인덱스 0~5 합집합, 서로 없는 곳은 NaN / sort=True : 인덱스 정렬
result5 = pd.concat([df2, sr1], axis=1, sort=True)
print(result5, '\n')

     a    b    c    d    e
0  NaN  NaN  NaN  NaN   e0
1  NaN  NaN  NaN  NaN   e1
2   a2   b2   c2   d2   e2
3   a3   b3   c3   d3   e3
4   a4   b4   c4   d4  NaN
5   a5   b5   c5   d5  NaN

In [122]:
# 시리즈 2개를 옆으로 → 데이터프레임 (열 e, g)
result6 = pd.concat([sr1, sr3], axis=1)
print(result6, '\n')

    e   g
0  e0  g0
1  e1  g1
2  e2  g2
3  e3  g3

In [123]:
# 시리즈 2개를 위아래로 → 긴 시리즈 1개 (인덱스 0~3 이 두 번 나옴)
result7 = pd.concat([sr1, sr3], axis=0)
print(result7, '\n')

0    e0
1    e1
2    e2
3    e3
0    g0
1    g1
2    g2
3    g3
dtype: str

#### 4-2.데이터프레임 병합(merge)
* key값을 중심으로 연결

In [124]:
import pandas as pd

# 기업의 기본정보 + 주가
# value : 시가총액
# 주의) 내 폴더에는 ./data/ 에 파일이 있음
df1 = pd.read_excel('./data/stock price.xlsx', engine= 'openpyxl')   # 주가데이터
df1.head()

       id stock_name          value   price
0  128940       한미약품   59385.666667  421000
1  130960     CJ E&M   58540.666667   98900
2  138250      엔에스쇼핑   14558.666667   13200
3  139480        이마트  239230.833333  254500
4  142280     녹십자엠에스     468.833333   10200

In [125]:
# 투자 판단을 위한 재무 재표
# eps : 주당 순이익(기업당 주당 벌어들이는 이익)
# bps : 주당 순자산가치
# per : 주가수익비율(주가 대비 수익 수준) = 주가 / eps → 낮을수록 저평가
# pbr : 주가자산비율(주가 대비 자산 가치) = 주가 / bps → 1 미만이면 자산보다 싸게 거래
df2 = pd.read_excel('./data/stock valuation.xlsx', engine= 'openpyxl')  # 밸류에이션
df2.head()

       id     name           eps     bps        per       pbr
0  130960   CJ E&M   6301.333333   54068  15.695091  1.829178
1  136480       하림    274.166667    3551  11.489362  0.887074
2  138040  메리츠금융지주   2122.333333   14894   6.313806  0.899691
3  139480      이마트  18268.166667  295780  13.931338  0.860437
4  145990      삼양사   5741.000000  108090  14.283226  0.758627

In [126]:
# 데이터프레임 합치기 - 교집합
# on 을 안 쓰면 이름이 같은 열(id)을 자동으로 key 로 사용
# 양쪽에 다 있는 id 5개만 남음
merge_inner = pd.merge(df1, df2)  # how 기본값 : inner(교집합)
print(merge_inner)

       id stock_name          value   price    name           eps     bps  \
0  130960     CJ E&M   58540.666667   98900  CJ E&M   6301.333333   54068
1  139480        이마트  239230.833333  254500     이마트  18268.166667  295780
2  145990        삼양사   82750.000000   82000     삼양사   5741.000000  108090
3  185750        종근당   40293.666667  100500     종근당   3990.333333   40684
4  204210     모두투어리츠    3093.333333    3475  모두투어리츠     85.166667    5335

         per       pbr
0  15.695091  1.829178
1  13.931338  0.860437
2  14.283226  0.758627
3  25.185866  2.470259
4  40.802348  0.651359

In [127]:
# 데이터프레임 합치기 - 합집합
# 한쪽에만 있는 id 도 다 남고, 없는 쪽 값은 NaN → 15행 (10 + 10 - 겹치는 5)
merge_outer = pd.merge(df1, df2, how='outer', on='id')  # how 기본값 : inner
print(merge_outer)

        id stock_name          value     price       name           eps  \
0   128940       한미약품   59385.666667  421000.0        NaN           NaN
1   130960     CJ E&M   58540.666667   98900.0     CJ E&M   6301.333333
2   136480        NaN            NaN       NaN         하림    274.166667
3   138040        NaN            NaN       NaN    메리츠금융지주   2122.333333
4   138250      엔에스쇼핑   14558.666667   13200.0        NaN           NaN
5   139480        이마트  239230.833333  254500.0        이마트  18268.166667
6   142280     녹십자엠에스     468.833333   10200.0        NaN           NaN
7   145990        삼양사   82750.000000   82000.0        삼양사   5741.000000
8   161390        NaN            NaN       NaN      한국타이어   5648.500000
9   181710        NaN            NaN       NaN  NHN엔터테인먼트   2110.166667
10  185750        종근당   40293.666667  100500.0        종근당   3990.333333
11  192400      쿠쿠홀딩스  179204.666667  177500.0        NaN           NaN
12  199800         툴젠   -2514.333333  115400.0        NaN           NaN
13  204210     모두투어리츠    3093.333333    3475.0     모두투어리츠     85.166667
14  207940        NaN            NaN       NaN   삼성바이오로직스   4644.166667

         bps        per       pbr
0        NaN        NaN       NaN
1    54068.0  15.695091  1.829178
2     3551.0  11.489362  0.887074
3    14894.0   6.313806  0.899691
4        NaN        NaN       NaN
5   295780.0  13.931338  0.860437
6        NaN        NaN       NaN
7   108090.0  14.283226  0.758627
8    51341.0   7.453306  0.820007
9    78434.0  30.755864  0.827447
10   40684.0  25.185866  2.470259
11       NaN        NaN       NaN
12       NaN        NaN       NaN
13    5335.0  40.802348  0.651359
14   60099.0  89.790059  6.938551

In [128]:
# 데이터프레임 합치기 - 왼쪽 데이터프레임 기준, 키 값 분리
# key 열 이름이 서로 다를 때 left_on / right_on 으로 각각 지정
# df1 은 전부 남김, 양쪽에 있는 id 열은 id_x(df1), id_y(df2) 로 이름이 바뀜
merge_left = pd.merge(df1, df2, how='left', left_on='stock_name', right_on='name')
print(merge_left)

     id_x stock_name          value   price      id_y    name           eps  \
0  128940       한미약품   59385.666667  421000       NaN     NaN           NaN
1  130960     CJ E&M   58540.666667   98900  130960.0  CJ E&M   6301.333333
2  138250      엔에스쇼핑   14558.666667   13200       NaN     NaN           NaN
3  139480        이마트  239230.833333  254500  139480.0     이마트  18268.166667
4  142280     녹십자엠에스     468.833333   10200       NaN     NaN           NaN
5  145990        삼양사   82750.000000   82000  145990.0     삼양사   5741.000000
6  185750        종근당   40293.666667  100500  185750.0     종근당   3990.333333
7  192400      쿠쿠홀딩스  179204.666667  177500       NaN     NaN           NaN
8  199800         툴젠   -2514.333333  115400       NaN     NaN           NaN
9  204210     모두투어리츠    3093.333333    3475  204210.0  모두투어리츠     85.166667

        bps        per       pbr
0       NaN        NaN       NaN
1   54068.0  15.695091  1.829178
2       NaN        NaN       NaN
3  295780.0  13.931338  0.860437
4       NaN        NaN       NaN
5  108090.0  14.283226  0.758627
6   40684.0  25.185866  2.470259
7       NaN        NaN       NaN
8       NaN        NaN       NaN
9    5335.0  40.802348  0.651359

In [129]:
# 데이터프레임 합치기 - 오른쪽 데이터프레임 기준, 키 값 분리
# df2 는 전부 남기고, df1 은 짝이 있는 것만
merge_right = pd.merge(df1, df2, how='right', left_on='stock_name', right_on='name')
print(merge_right)

       id_x stock_name          value     price    id_y       name  \
0  130960.0     CJ E&M   58540.666667   98900.0  130960     CJ E&M
1       NaN        NaN            NaN       NaN  136480         하림
2       NaN        NaN            NaN       NaN  138040    메리츠금융지주
3  139480.0        이마트  239230.833333  254500.0  139480        이마트
4  145990.0        삼양사   82750.000000   82000.0  145990        삼양사
5       NaN        NaN            NaN       NaN  161390      한국타이어
6       NaN        NaN            NaN       NaN  181710  NHN엔터테인먼트
7  185750.0        종근당   40293.666667  100500.0  185750        종근당
8  204210.0     모두투어리츠    3093.333333    3475.0  204210     모두투어리츠
9       NaN        NaN            NaN       NaN  207940   삼성바이오로직스

            eps     bps        per       pbr
0   6301.333333   54068  15.695091  1.829178
1    274.166667    3551  11.489362  0.887074
2   2122.333333   14894   6.313806  0.899691
3  18268.166667  295780  13.931338  0.860437
4   5741.000000  108090  14.283226  0.758627
5   5648.500000   51341   7.453306  0.820007
6   2110.166667   78434  30.755864  0.827447
7   3990.333333   40684  25.185866  2.470259
8     85.166667    5335  40.802348  0.651359
9   4644.166667   60099  89.790059  6.938551

In [130]:
# price가 50000미만인 종목을 찾기 
    # 1.df1에서 price가 5만원 미만인 값을 추출(mask 연산)
    # 2.merge를 통해 결합

In [ ]:
# 1. price 가 5만원 미만인 행만 → 엔에스쇼핑, 녹십자엠에스, 모두투어리츠
mask = df1['price'] < 50000
price = df1[mask]
print(price.head())

In [ ]:
# 2. 재무 정보와 결합 → 모두투어리츠 1개만 남음 (나머지 2개는 df2 에 없음)
value = pd.merge(price, df2)  # 교집합
print(value)

In [133]:
# price가 1만 초과 & 5만 미만인 종목 찾기
# 걸러진 2종목이 df2 에 없어서 merge 결과는 Empty DataFrame
mask =  (df1['price'] > 10000) & (df1['price'] < 50000)
price = df1[mask]
value = pd.merge(price, df2)  # 교집합
print(price)
print()
print(value)

       id stock_name         value  price
2  138250      엔에스쇼핑  14558.666667  13200
4  142280     녹십자엠에스    468.833333  10200

Empty DataFrame
Columns: [id, stock_name, value, price, name, eps, bps, per, pbr]
Index: []

#### 4-3.데이터프레임 결합(Join)

In [134]:
import pandas as pd

df1 = pd.read_excel('./data/stock price.xlsx', engine= 'openpyxl')
df2 = pd.read_excel('./data/stock valuation.xlsx', engine= 'openpyxl')  # 밸류에이션

In [135]:
# join 은 행 인덱스 기준으로 합침
# 인덱스 설정 없이 쓰면 0번 줄끼리, 1번 줄끼리 붙음 → 종목이 안 맞는 잘못된 결과 (에러는 안 남)
# lsuffix : df1에 중복된 이름의 뒤에 _price를 붙임
# rsuffix : df2에 중복된 이름의 뒤에 _val를 붙임
df3 = df1.join(df2, lsuffix='_price', rsuffix='_val')
print(df3)

   id_price stock_name          value   price  id_val       name  \
0    128940       한미약품   59385.666667  421000  130960     CJ E&M
1    130960     CJ E&M   58540.666667   98900  136480         하림
2    138250      엔에스쇼핑   14558.666667   13200  138040    메리츠금융지주
3    139480        이마트  239230.833333  254500  139480        이마트
4    142280     녹십자엠에스     468.833333   10200  145990        삼양사
5    145990        삼양사   82750.000000   82000  161390      한국타이어
6    185750        종근당   40293.666667  100500  181710  NHN엔터테인먼트
7    192400      쿠쿠홀딩스  179204.666667  177500  185750        종근당
8    199800         툴젠   -2514.333333  115400  204210     모두투어리츠
9    204210     모두투어리츠    3093.333333    3475  207940   삼성바이오로직스

            eps     bps        per       pbr
0   6301.333333   54068  15.695091  1.829178
1    274.166667    3551  11.489362  0.887074
2   2122.333333   14894   6.313806  0.899691
3  18268.166667  295780  13.931338  0.860437
4   5741.000000  108090  14.283226  0.758627
5   5648.500000   51341   7.453306  0.820007
6   2110.166667   78434  30.755864  0.827447
7   3990.333333   40684  25.185866  2.470259
8     85.166667    5335  40.802348  0.651359
9   4644.166667   60099  89.790059  6.938551

In [136]:
import pandas as pd

df1 = pd.read_excel('./data/stock price.xlsx', engine= 'openpyxl')
df2 = pd.read_excel('./data/stock valuation.xlsx', engine= 'openpyxl')  # 밸류에이션

# key(id)를 행 인덱스로 먼저 설정 (inplace=True : 원본을 바로 바꿈)
df1.set_index('id', inplace=True)
df2.set_index('id', inplace=True)

# 같은 id 끼리 붙음. 기본값 how='left' → df1 10행 유지, df2 에 없는 종목은 NaN
df = df1.join(df2)
df.head()

,stock_name,value,price,name,eps,bps,per,pbr
id,,,,,,,,
128940,한미약품,59385.666667,421000,NaN,NaN,NaN,NaN,NaN
130960,CJ E&M,58540.666667,98900,CJ E&M,6301.333333,54068.0,15.695091,1.829178
138250,엔에스쇼핑,14558.666667,13200,NaN,NaN,NaN,NaN,NaN
139480,이마트,239230.833333,254500,이마트,18268.166667,295780.0,13.931338,0.860437
142280,녹십자엠에스,468.833333,10200,NaN,NaN,NaN,NaN,NaN

## 5.그룹 연산

#### 5-1.그룹 객체 만들기(분할 단계)

* 1개 열을 기준으로 그룹화

In [137]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','sex', 'class', 'fare', 'survived']]

print('승객 수:', len(df))     # 891

승객 수: 891

In [138]:
# class 기준으로 분할 → 아직 계산 전, 나눠만 놓은 그룹 객체
# 리스트로 넣으면 key 가 튜플 ('First',) 로 나옴
grouped = df.groupby(['class'])
for key, group in grouped:        # 그룹 객체는 for 로 하나씩 꺼낼 수 있음
    print(type(key), type(group))
    print('* key :', key)
    print('* number :', len(group))    # First 216 / Second 184 / Third 491
    print(group.head())
    print('\n')

<class 'tuple'> <class 'pandas.DataFrame'>
* key : ('First',)
* number : 216
     age     sex  class     fare  survived
1   38.0  female  First  71.2833         1
3   35.0  female  First  53.1000         1
6   54.0    male  First  51.8625         0
11  58.0  female  First  26.5500         1
23  28.0    male  First  35.5000         1


<class 'tuple'> <class 'pandas.DataFrame'>
* key : ('Second',)
* number : 184
     age     sex   class     fare  survived
9   14.0  female  Second  30.0708         1
15  55.0  female  Second  16.0000         1
17   NaN    male  Second  13.0000         1
20  35.0    male  Second  26.0000         0
21  34.0    male  Second  13.0000         1


<class 'tuple'> <class 'pandas.DataFrame'>
* key : ('Third',)
* number : 491
    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
2  26.0  female  Third   7.9250         1
4  35.0    male  Third   8.0500         0
5   NaN    male  Third   8.4583         0
7   2.0    male  Third  21.0750         0

In [139]:
# 연산 메소드 적용
# numeric_only=True : 숫자 열만 평균 (sex 같은 글자 열이 있으면 TypeError)
# survived 는 0/1 이라 평균 = 생존율
average = grouped.mean(numeric_only=True)
print(average)

              age       fare  survived
class
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

In [140]:
# 개별 그룹 선택 (리스트로 groupby 했으니 key 도 튜플로)
group3 = grouped.get_group(('Third',))
print(group3.head())
group3

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
2  26.0  female  Third   7.9250         1
4  35.0    male  Third   8.0500         0
5   NaN    male  Third   8.4583         0
7   2.0    male  Third  21.0750         0

      age     sex  class     fare  survived
0    22.0    male  Third   7.2500         0
2    26.0  female  Third   7.9250         1
4    35.0    male  Third   8.0500         0
5     NaN    male  Third   8.4583         0
7     2.0    male  Third  21.0750         0
..    ...     ...    ...      ...       ...
882  22.0  female  Third  10.5167         0
884  25.0    male  Third   7.0500         0
885  39.0  female  Third  29.1250         0
888   NaN  female  Third  23.4500         0
890  32.0    male  Third   7.7500         0

[491 rows x 5 columns]

* 여러 열을 기준으로 그룹화

In [141]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','sex', 'class', 'fare', 'survived']]

print('승객 수:', len(df))

승객 수: 891

In [ ]:
# class 열, sex 열을 기준으로 분할 → 3 x 2 = 6개 그룹
# key 는 ('First', 'female') 처럼 튜플
grouped_two = df.groupby(['class', 'sex'])
for key, group in grouped_two:
    print('* key :', key)
    print('* number :', len(group))
    print(group.head())
    print('\n')

In [143]:
# 3등석 여성 그룹만 꺼내기
group3f = grouped_two.get_group(('Third','female'))
print(group3f.head())

     age     sex  class     fare  survived
2   26.0  female  Third   7.9250         1
8   27.0  female  Third  11.1333         1
10   4.0  female  Third  16.7000         1
14  14.0  female  Third   7.8542         0
18  31.0  female  Third  18.0000         0

In [144]:
# 그룹 6개 각각의 평균 → 행 인덱스가 (class, sex) 2단 = 멀티 인덱스
average_two = grouped_two.mean(numeric_only=True)
print(average_two)
print('\n')
print(type(average_two))

                     age        fare  survived
class  sex
First  female  34.611765  106.125798  0.968085
       male    41.281386   67.226127  0.368852
Second female  28.722973   21.970121  0.921053
       male    30.740707   19.741782  0.157407
Third  female  21.750000   16.118810  0.500000
       male    26.507589   12.661633  0.135447


<class 'pandas.DataFrame'>

In [145]:
def min_max(x):    # 최대값 - 최소값
    return x.max() - x.min()

# 열마다 적용할 함수를 딕셔너리로 지정 (내가 만든 함수도 가능)
agg_minmax = grouped.agg({
    'age': min_max,
    'fare': min_max,
    'survived': min_max
})

agg_minmax

          age      fare  survived
class
First   79.08  512.3292         1
Second  69.33   73.5000         1
Third   73.58   69.5500         1

In [146]:
# 여러 함수를 각 열에 동일하게 적용하여 집계
# sex(글자)도 min/max 가 나오는데 알파벳 순이라 의미 없음
agg_all = grouped.agg(['min', 'max'])
print(agg_all.head())

         age           sex       fare           survived
         min   max     min   max  min       max      min max
class
First   0.92  80.0  female  male  0.0  512.3292        0   1
Second  0.67  70.0  female  male  0.0   73.5000        0   1
Third   0.42  74.0  female  male  0.0   69.5500        0   1

In [147]:
# 각 열마다 다른 함수를 적용하여 집계
agg_sep = grouped.agg({'fare':['min', 'max'], 'age':'mean'})
print(agg_sep.head())

       fare                  age
        min       max       mean
class
First   0.0  512.3292  38.233441
Second  0.0   73.5000  29.877630
Third   0.0   69.5500  25.140620

In [148]:
# 열 하나만 골라서 계산 (grouped['age'].mean() 과 같음)
age_mean = grouped.age.mean(numeric_only=True)
print(age_mean)

class
First     38.233441
Second    29.877630
Third     25.140620
Name: age, dtype: float64

*  그룹 객체 필터링

In [ ]:
# 데이터 개수가 200개 이상인 그룹만을 필터링하여 데이터프레임으로 반환
# x = 그룹 하나(데이터프레임) → First(216), Third(491) 통과 / Second(184) 탈락
# 결과는 요약표가 아니라 통과한 그룹의 원래 행들
grouped_filter = grouped.filter(lambda x: len(x) >= 200)
print(grouped_filter.head())
print('\n')
print(type(grouped_filter))

In [150]:
# age 열의 평균이 30보다 작은 그룹만을 필터링하여 데이터프레임으로 반환
# Second(29.9), Third(25.1) 통과 / First(38.2) 탈락
age_filter = grouped.filter(lambda x: x.age.mean() < 30)
print(age_filter.tail())
print('\n')
print(type(age_filter))

      age     sex   class    fare  survived
884  25.0    male   Third   7.050         0
885  39.0  female   Third  29.125         0
886  27.0    male  Second  13.000         0
888   NaN  female   Third  23.450         0
890  32.0    male   Third   7.750         0


<class 'pandas.DataFrame'>

## 멀티 인덱스

In [151]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','sex', 'class', 'fare', 'survived']]

grouped = df.groupby(['class', 'sex'])    # 2개 열로 그룹 → 결과 인덱스가 멀티 인덱스

In [152]:
# class, sex 가 인덱스로 빠져서 남은 열이 전부 숫자 → numeric_only 없어도 됨
gdf = grouped.mean()
print(gdf)
print('\n')
print(type(gdf))

                     age        fare  survived
class  sex
First  female  34.611765  106.125798  0.968085
       male    41.281386   67.226127  0.368852
Second female  28.722973   21.970121  0.921053
       male    30.740707   19.741782  0.157407
Third  female  21.750000   16.118810  0.500000
       male    26.507589   12.661633  0.135447


<class 'pandas.DataFrame'>

In [153]:
# class 값이 First인 행을 선택하여 출력 (바깥 레벨)
print(gdf.loc['First'])

              age        fare  survived
sex
female  34.611765  106.125798  0.968085
male    41.281386   67.226127  0.368852

In [154]:
# class 값이 First이고, sex 값이 female인 행을 선택하여 출력 → 한 줄(시리즈)
print(gdf.loc[('First', 'female')])

age          34.611765
fare        106.125798
survived      0.968085
Name: (First, female), dtype: float64

In [155]:
# sex 값이 male인 행을 선택하여 출력
# loc 은 바깥 레벨부터만 지정 가능 → 안쪽 레벨(sex)로 고를 땐 xs 사용
print(gdf.xs('male', level='sex'))

              age       fare  survived
class
First   41.281386  67.226127  0.368852
Second  30.740707  19.741782  0.157407
Third   26.507589  12.661633  0.135447

## 피벗
* 구성 4가지 요소 : 행 인덱스, 열 인덱스, 데이터 값, 데이터 집계 함수

In [ ]:
# 등급별, 성별 평균 나이 (groupby 결과를 가로세로 표로 펼친 모양)
pdf1 = pd.pivot_table(df,             # 피벗할 데이터프레임
                      index='class',    # 행 위치에 들어갈 열
                      columns='sex',    # 열 위치에 들어갈 열
                      values='age',     # 데이터로 사용할 열
                      aggfunc='mean')   # 데이터 집계 함수

print(pdf1.head())

In [158]:
# class별, 성별, 생존율, 생존자 수 집계(mean, sum), value : survived
# survived 가 0/1 이라 mean = 생존율, sum = 생존자 수
# 함수가 2개라 열 인덱스가 (함수, sex) 2단으로 생김
pdf2 = pd.pivot_table(df,                      # 피벗할 데이터프레임
                      index='class',             # 행 위치에 들어갈 열
                      columns='sex',             # 열 위치에 들어갈 열
                      values='survived',         # 데이터로 사용할 열
                      aggfunc=['mean', 'sum'])   # 데이터 집계 함수

pdf2.head()

            mean              sum
sex       female      male female male
class
First   0.968085  0.368852     91   45
Second  0.921053  0.157407     70   17
Third   0.500000  0.135447     72   47

In [159]:
# class, sex 별 평균나이, 최대 요금
# 열 인덱스 3단 : (함수, 값, survived) → 2 x 2 x 2 = 8개 열

pdf3 = pd.pivot_table(df,                      # 피벗할 데이터프레임
                    index=['class', 'sex'],    # 행 위치에 들어갈 열
                    columns='survived',        # 열 위치에 들어갈 열
                    values=['age', 'fare'],    # 데이터로 사용할 열
                    aggfunc=['mean', 'max'])   # 데이터 집계 함수

pdf3.head()

# 1등급 여성중 생존자의 평균 나이 : 34.939

                    mean                                      max        \
                     age                   fare               age
survived               0          1           0           1     0     1
class  sex
First  female  25.666667  34.939024  110.604167  105.978159  50.0  63.0
       male    44.581967  36.248000   62.894910   74.637320  71.0  80.0
Second female  36.000000  28.080882   18.250000   22.288989  57.0  55.0
       male    33.369048  16.022000   19.488965   21.095100  70.0  62.0
Third  female  23.818182  19.329787   19.773093   12.464526  48.0  63.0


                 fare
survived            0         1
class  sex
First  female  151.55  512.3292
       male    263.00  512.3292
Second female   26.00   65.0000
       male     73.50   39.0000
Third  female   69.55   31.3875

In [160]:
# 행, 열 구조 살펴보기
print(pdf3.index)       # MultiIndex (class, sex)
print(pdf3.columns)     # MultiIndex (함수, 값, survived)

MultiIndex([( 'First', 'female'),
            ( 'First',   'male'),
            ('Second', 'female'),
            ('Second',   'male'),
            ( 'Third', 'female'),
            ( 'Third',   'male')],
           names=['class', 'sex'])
MultiIndex([('mean',  'age', 0),
            ('mean',  'age', 1),
            ('mean', 'fare', 0),
            ('mean', 'fare', 1),
            ( 'max',  'age', 0),
            ( 'max',  'age', 1),
            ( 'max', 'fare', 0),
            ( 'max', 'fare', 1)],
           names=[None, None, 'survived'])

In [161]:
# xs 인덱서 사용 - 행 선택(default: axis=0)
# 바깥 레벨 class 가 First 인 행들
print(pdf3.xs('First'))

               mean                                      max                \
                age                   fare               age          fare
survived          0          1           0           1     0     1       0
sex
female    25.666667  34.939024  110.604167  105.978159  50.0  63.0  151.55
male      44.581967  36.248000   62.894910   74.637320  71.0  80.0  263.00



survived         1
sex
female    512.3292
male      512.3292

In [162]:
# 행 인덱스가 ('First', 'female')인 행을 선택
print(pdf3.xs(('First', 'female')))

            survived
mean  age   0            25.666667
            1            34.939024
      fare  0           110.604167
            1           105.978159
max   age   0            50.000000
            1            63.000000
      fare  0           151.550000
            1           512.329200
Name: (First, female), dtype: float64

In [163]:
# 행 인덱스의 sex 레벨이 male인 행을 선택
print(pdf3.xs('male', level='sex'))

               mean                                    max                \
                age                  fare              age          fare
survived          0          1          0          1     0     1       0
class
First     44.581967  36.248000  62.894910  74.637320  71.0  80.0  263.00
Second    33.369048  16.022000  19.488965  21.095100  70.0  62.0   73.50
Third     27.255814  22.274211  12.204469  15.579696  74.0  45.0   69.55



survived         1
class
First     512.3292
Second     39.0000
Third      56.4958

In [164]:
 # Second, male인 행을 선택
 # level 은 번호(0)와 이름('sex')을 섞어 써도 됨
print(pdf3.xs(('Second', 'male'), level=[0, 'sex']))

                  mean                               max
                   age               fare            age        fare
survived             0       1          0        1     0     1     0     1
class  sex
Second male  33.369048  16.022  19.488965  21.0951  70.0  62.0  73.5  39.0

In [165]:
# xs 인덱서 사용 - 열 선택(axis=1 설정)
# axis=1 을 안 쓰면 행에서 찾음
print(pdf3.xs('mean', axis=1))

                     age                   fare
survived               0          1           0           1
class  sex
First  female  25.666667  34.939024  110.604167  105.978159
       male    44.581967  36.248000   62.894910   74.637320
Second female  36.000000  28.080882   18.250000   22.288989
       male    33.369048  16.022000   19.488965   21.095100
Third  female  23.818182  19.329787   19.773093   12.464526
       male    27.255814  22.274211   12.204469   15.579696

In [ ]:
# 열 인덱스가 ('mean', 'age')인 데이터 선택 → 사망(0)/생존(1)별 평균 나이
print(pdf3.xs(('mean', 'age'), axis=1))

In [167]:
# survived 레벨이 1인 데이터 선택 → 생존자 열만
print(pdf3.xs(1, level='survived', axis=1))

                    mean               max
                     age        fare   age      fare
class  sex
First  female  34.939024  105.978159  63.0  512.3292
       male    36.248000   74.637320  80.0  512.3292
Second female  28.080882   22.288989  55.0   65.0000
       male    16.022000   21.095100  62.0   39.0000
Third  female  19.329787   12.464526  63.0   31.3875
       male    22.274211   15.579696  45.0   56.4958

In [ ]:
# max, fare, survived=0인 데이터 선택 → 사망자의 최대 요금
# level 을 지정하면 꺼낸 레벨 이름이 결과에 그대로 남음
print(pdf3.xs(('max', 'fare', 0),
              level=[0, 1, 2], axis=1))