In [32]:
''' 
1.함수 매핑
    1-1.개별 원소에 함수 매핑
        * 시리즈 원소에 함수 매핑
        * 데이터프레임 원소에 함수 매핑
    1-2.시리즈 객체에 함수 매핑
        * 데이터프레임의 각 열에 함수 매핑
            ** 리턴값이 시리즈
            ** 리턴값이 원소
        * 데이터프레임의 각 행에 함수 매핑
    1-3.데이터프레임 객체에 함수 매핑
'''

' \n1.함수 매핑\n    1-1.개별 원소에 함수 매핑\n        * 시리즈 원소에 함수 매핑\n        * 데이터프레임 원소에 함수 매핑\n    1-2.시리즈 객체에 함수 매핑\n        * 데이터프레임의 각 열에 함수 매핑\n            ** 리턴값이 시리즈\n            ** 리턴값이 원소\n        * 데이터프레임의 각 행에 함수 매핑\n    1-3.데이터프레임 객체에 함수 매핑\n'

## 1.함수 매핑

#### 1-1.개별 원소에 함수 매핑

* 시리즈 원소에 함수 매핑

In [33]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]
df['ten'] = 10
print(df.head())

    age     fare  ten
0  22.0   7.2500   10
1  38.0  71.2833   10
2  26.0   7.9250   10
3  35.0  53.1000   10
4  35.0   8.0500   10

In [34]:
# 사용자 함수 정의
def add_10(n):   # 10을 더하는 함수
    return n + 10

def add_two_obj(a, b):    # 두 객체의 합
    return a + b

In [35]:
print(add_10(10))
print(add_two_obj(10, 10))

20
20

In [36]:
# 시리즈 객체에 적용
sr1 = df['age'].apply(add_10)   
print(sr1.head())

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [37]:
# # test code
# def add_10(n):
#     print("처리중:", n)
#     return n + 10

# df['age'].apply(add_10)

In [38]:
# 시리즈 객체와 숫자에 적용 : 2개의 인수(시리즈 + 숫자)
sr2 = df['age'].apply(add_two_obj, b=10) 
print(sr2.head())

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [39]:
# 람다 함수 활용: 시리즈 객체에 적용
# sr3 = df['age'].apply(lambda x: add_10(x)) 
sr3 = df['age'].apply(lambda x: add_10(x) if x % 2 == 0 else x)
print(sr3.head())

0    32.0
1    48.0
2    36.0
3    35.0
4    35.0
Name: age, dtype: float64

* 데이터프레임 원소에 함수 매핑

In [40]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]

print(df.head())

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [41]:
def add_10(n):   # 10을 더하는 함수
    return n + 10

In [42]:
df_map = df.map(add_10)   
print(df_map.head())

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

* 금융 sample

In [43]:
import pandas as pd

df = pd.DataFrame({
    '종목': ['삼성전자', 'SK하이닉스', '현대차', '카카오'],
    '종가': [70000, 180000, 250000, 55000],
    '수익률(%)': [2.5, -1.2, 3.8, -0.5],
    '거래량': [1000000, 800000, 450000, 1200000]
})

print(df)

       종목      종가  수익률(%)      거래량
0    삼성전자   70000     2.5  1000000
1  SK하이닉스  180000    -1.2   800000
2     현대차  250000     3.8   450000
3     카카오   55000    -0.5  1200000

** 시리즈 원소에 함수 매핑

In [44]:
# 예제 1. 종가에 10% 목표 수익률 적용
def target_price(price):
    return price * 1.10

# 종가 시리즈에 함수 매핑 : '목표가' 변수명 추가
df['목표가'] = df['종가'].apply(target_price)
# df['목표가'] = df['종가'].map(target_price)
df.head()

       종목      종가  수익률(%)      거래량       목표가
0    삼성전자   70000     2.5  1000000   77000.0
1  SK하이닉스  180000    -1.2   800000  198000.0
2     현대차  250000     3.8   450000  275000.0
3     카카오   55000    -0.5  1200000   60500.0

In [45]:
# 예제 2. 수익률에 따라 매수·매도 신호 만들기
def trading_signal(rate):
    if rate >= 3:
        return '강한 상승'
    elif rate > 0:
        return '상승'
    elif rate <= -1:
        return '하락'
    else:
        return '약보합'

df['시장신호'] = df['수익률(%)'].apply(trading_signal)
df.head()

       종목      종가  수익률(%)      거래량       목표가   시장신호
0    삼성전자   70000     2.5  1000000   77000.0     상승
1  SK하이닉스  180000    -1.2   800000  198000.0     하락
2     현대차  250000     3.8   450000  275000.0  강한 상승
3     카카오   55000    -0.5  1200000   60500.0    약보합

In [46]:
# 예제 3. 종가가 100,000원 이상이면 목표가 계산, 미만이면 0

# 목표가 계산 함수: 종가 대비 10% 상승
def target_price(price):
    return price * 1.10

df['목표가'] = df['종가'].apply(
    lambda x: target_price(x) if x >= 100000 else 0
)

df.head()

       종목      종가  수익률(%)      거래량       목표가   시장신호
0    삼성전자   70000     2.5  1000000       0.0     상승
1  SK하이닉스  180000    -1.2   800000  198000.0     하락
2     현대차  250000     3.8   450000  275000.0  강한 상승
3     카카오   55000    -0.5  1200000       0.0    약보합

** 데이터프레임 원소에 함수 매핑

In [48]:
prices = pd.DataFrame({
    '삼성전자': [70000, 71000, 72000],
    'SK하이닉스': [180000, 182000, 185000]
}, index=['월요일', '화요일', '수요일'])

In [49]:
# 예제 4. 금융 수치 전체를 천 원 단위로 변환
def to_thousand(x):
    return x / 1000

result = prices.map(to_thousand)
result

     삼성전자  SK하이닉스
월요일  70.0   180.0
화요일  71.0   182.0
수요일  72.0   185.0

In [50]:
# 예제 5. 데이터프레임의 숫자를 등급으로 변환
scores = pd.DataFrame({
    '삼성전자': [90, 65, 30],
    'SK하이닉스': [75, 95, 45]
}, index=['상승점수', '안정점수', '위험점수'])

def grade(score):
    if score >= 80:
        return 'A'
    elif score >= 60:
        return 'B'
    else:
        return 'C'

result = scores.map(grade)
result

     삼성전자 SK하이닉스
상승점수    A      B
안정점수    B      A
위험점수    C      C

#### 1-2.시리즈 객체에 함수 매핑

* 데이터프레임의 각 열에 함수 매핑

** 리턴값이 시리즈

In [55]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]

print(df.head())

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [56]:
# 사용자 함수 정의
def missing_value(series):    # 시리즈를 인수로 전달
    return series.isnull()    # 불린(Boolean) 시리즈를 반환

# 데이터프레임의 각 열을 인수로 전달하면 데이터프레임을 반환
result = df.apply(missing_value, axis=0)  
print(result.head())
print('\n')
print(type(result))

     age   fare
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False


<class 'pandas.DataFrame'>

** 리턴값이 원소

In [57]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]

print(df.head())

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [54]:
def min_max(x):
    return x.max() - x.min()

# 데이터프레임의 각 열을(시리즈) 인수로 전달하면 시리즈를 반환
result = df.apply(min_max)   #기본값 axis=0 
print(result)
print('\n')
print(type(result))

age      79.5800
fare    512.3292
dtype: float64


<class 'pandas.Series'>

* 데이터프레임의 각 행에 함수 매핑

In [58]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]
df['ten'] = 10
print(df.head())

    age     fare  ten
0  22.0   7.2500   10
1  38.0  71.2833   10
2  26.0   7.9250   10
3  35.0  53.1000   10
4  35.0   8.0500   10

In [59]:
def add_two_obj(a, b): 
    return a + b  

df['add'] = df.apply(lambda x: add_two_obj(x['age'], x['ten']), axis=1)   # 행 연산
print(df.head())

    age     fare  ten   add
0  22.0   7.2500   10  32.0
1  38.0  71.2833   10  48.0
2  26.0   7.9250   10  36.0
3  35.0  53.1000   10  45.0
4  35.0   8.0500   10  45.0

#### 1-3.데이터프레임 객체에 함수 매핑

In [ ]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','fare']]
print(df.head())

In [60]:
# 각 열의 NaN 찾기 - 데이터프레임 전달하면 데이터프레임을 반환
def missing_value(x):    
    return x.isnull()    

# 각 열의 NaN 개수 반환 - 데이터프레임 전달하면 시리즈 반환
def missing_count(x):    # 
    return missing_value(x).sum()

# 데이터프레임의 총 NaN 개수 - 데이터프레임 전달하면 값을 반환
def total_number_missing(x):    
    return missing_count(x).sum()

result_df = df.pipe(missing_value)   
print(result_df.head())
print(type(result_df))

     age   fare    ten    add
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
<class 'pandas.DataFrame'>

In [61]:
result_series = df.pipe(missing_count)   
print(result_series)
print(type(result_series))

age     177
fare      0
ten       0
add     177
dtype: int64
<class 'pandas.Series'>

In [62]:
result_value = df.pipe(total_number_missing)   
print(result_value)
print(type(result_value))

354
<class 'numpy.int64'>